### ISSUE TITLE
Use `arg_num!` instead of custom enum implementation

### ISSUE THREAD

**Issue by Byron** [Byron/google-apis-rs#101]
Once [this PR](https://github.com/kbknapp/clap-rs/pull/105) is available in the main stream, we can start getting rid of some 'stupid' code. And less code is better.

**Comment by Byron** [comment]
Unfortunately `arg_enum!` doesn't yet work as advertised. Will reopen, once fixed.

**Comment by kbknapp** [comment]
Should be good to go now, I've added some tests too to ensure it doesn't break in the future.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/FB0CRta4GhE).
