### ISSUE TITLE
build failing?

### ISSUE THREAD

**Issue by steveklabnik** [Byron/google-apis-rs#124]
crater is showing these APIs as failing: https://tools.taskcluster.net/task-inspector/#dRl5GfDCQv2bUl0-6y7dRQ/0

they fail on my local machine in the same way. but your travis build is passing, even though i'm running the same commands. Any ideas?

**Comment by Byron** [comment]
Thanks for letting me know. The last version I successfully compiled with is `hyper=0.6.4`, the `Cargo.toml` however is setup to allow later versions as well.
In the same moment I realized that serde will not compile anymore either as `serde::json` was moved into its own crate.

I will fix the issues soon and post updates here accordingly.
