### ISSUE TITLE
tips for getting started with calendar lib

### ISSUE THREAD

**Issue by softprops** [Byron/google-apis-rs#127]
I'd like to use your calendar v3 interface as a lib. I'm struggling. a bit on how to get up and running. I've dug to through the source and have a general sense for the patterns applied but I could use some input on piecing them together.

It took a bit of debugging but here's what I have so far

I can set up a new `ApplicationSecret` from a json file containing api credentials.

```rust
  let secret: ApplicationSecret =
    json::from_str::<ConsoleApplicationSecret>(
      credential_json
    )
    .unwrap()
    .installed
    .unwrap();
```

I've found that ever run requires an extra context switch to authorize the run with a code printed to stdout. I'd like to avoid that with my app and self-authorize this client once for my own google account. In order to do so I had to wrap the memory store with a store that printed out a token the memory store gets
after a successful device poll + remote authorization.

```rust
struct LoggedTokenStorage {
  memory: MemoryStorage
}

impl TokenStorage for LoggedTokenStorage {
  type Error = <MemoryStorage as TokenStorage>::Error;
  fn set(
    &mut self, scope_hash: u64, scopes: &Vec<&str>, token: Option<Token>
  ) -> std::result::Result<(), Self::Error> {
    println!(
      "{:?} - {:?} - {:?}", scope_hash, scopes, token
      );
    self.memory.set(scope_hash, scopes, token)
  }

  fn get(
    &self, scope_hash: u64, scopes: &Vec<&str>
  ) -> std::result::Result<Option<Token>, Self::Error> {
    println!(
      "{:?} - {:?}", scope_hash, scopes
     );
    self.memory.get(scope_hash, scopes)
  }
}
```

with the access token authorized with the calendar scope on hand, I thought afterwards I could manually reconstruct that token ( which doesn't appear to have an expires_in value ) and set in on the memory store on startup and avoid future interactive prompts. so far, so good

```rust

  let mut tokens = LoggedTokenStorage {
    memory: <MemoryStorage as Default>::default(),
  };

  tokens.set( hand constructed token );

  let auth = Authenticator::new(
    &secret,
    DefaultAuthenticatorDelegate,
    hyper::Client::new(),
    tokens,
    None
  );

  let mut hub = CalendarHub::new(
    hyper::Client::new(), auth
  );

  let result = hub.events()
    .list("primary")
    .add_scope(Scope::Full)
    .doit();
```

when the request for events is sent, I always 403 error

```rust
Err(Failure(Response { status: Forbidden, headers: Headers { Date: Tue, 13 Oct 2015 00:19:57 GMT, Accept-Ranges: none, Alternate-Protocol: 443:quic,p=1, X-Frame-Options: SAMEORIGIN, Cache-Control: private, max-age=0, Alt-Svc: quic=":443"; p="1"; ma=604800, X-XSS-Protection: 1; mode=block, X-Content-Type-Options: nosniff, Transfer-Encoding: chunked, Server: GSE, Expires: Tue, 13 Oct 2015 00:19:57 GMT, Vary: X-OriginOrigin,Accept-Encoding, Content-Type: application/json; charset=UTF-8, }, version: Http11, url: Url { scheme: "https", scheme_data: Relative(RelativeSchemeData { username: "", password: None, host: Domain("www.googleapis.com"), port: None, default_port: Some(443), path: ["calendar", "v3", "calendars", "primary", "events"] }), query: Some("alt=json"), fragment: None }, status_raw: RawStatus(403, "Forbidden"), message: Http11Message { method: None, stream: Wrapper { obj: Some(Reading(ChunkedReader(chunk_remaining=0))) } } }))
```

I'm kind of stuck with where to go from here. Are there any other getting started tips for library users?

**Comment by softprops** [comment]
after a bit more debugging this morning. this appears to be a bit of user error. It wasn't clear from google's api docs that you need to enable access to an api after generating a set credentials in order to starting issuing requests. I traced this back a bit by reconstructing a curl request with the access token I was testing with. the json that came back from googles servers added a bit more context.

feel free to close this gh issue if you want. It may be helpful to other library users in the future for reference.

**Comment by Byron** [comment]
Thanks for writing about your interaction with the library. I indeed wanted to make it as user-friendly as possible, so every 'user story' is much appreciated.

Where do you think should additional information be placed ? On the main landing page of the API docs maybe ?

**Comment by Byron** [comment]
I am closing this issue due to prolonged inactivity.
Also I recommend recompiling the latest version - it supports a new authentication flow which usually opens up all abilities of the respective API.
