### ISSUE TITLE
CLI parsing does not match docs

### ISSUE THREAD

**Issue by simcop2387** [Byron/google-apis-rs#128]
This is at least on youtube3-cli specifically.

The docs show doing the request parameters as follows for inserting a live-stream
```
youtube3 live-streams insert -r .cdn format=720p
```

This results in an error, 
```
error: The following required arguments were not supplied:

USAGE:
        youtube3 live-streams insert [FLAGS] [OPTIONS] -r <kv>...

For more information try --help
```

It appears to be expecting the key value to be directly after the -r with no spaces, which is fine, but has other problems:

```
% ./youtube3 --debug live-streams insert -r'.cdn format=720p'
Field -> Field 'cdn format' does not exist. Did you mean '.format=720p' ?
```

I can set the key by doing, this:
```
% ./youtube3 --debug live-streams insert -r'.cdn.format=720p'
POST /youtube/v3/liveStreams?part=cdn&alt=json HTTP/1.1
...Headers removed...

{"cdn":{"format":"720p"}}HTTP/1.1 400 Bad Request
```

And get a 400 bad request, because as per the youtube api docs, i need to specify a few more keys.  But despite the docs for youtube3-cli saying you can, there doesn't actually appear to be a way to do so.

Addng another -r results in this again:
````
% ./youtube3 --debug live-streams insert -r'.cdn.format=720p' -r'.cdn.ingestion-type=rtmp'
error: The following required arguments were not supplied:

USAGE:
        youtube3 live-streams insert [FLAGS] [OPTIONS] -r <kv>...

For more information try --help
```

Trying to do it all in one string causes it to become part of the format:
```
% ./youtube3 --debug live-streams insert -r'.cdn.format=720p .cdn.ingestion-type=rtmp'    
POST /youtube/v3/liveStreams?part=cdn&alt=json HTTP/1.1
...Headers removed

{"cdn":{"format":"720p .cdn.ingestion-type=rtmp"}}
```

And giving it as a second string after the -r gives an error about it being unexpected:
```
% ./youtube3 --debug live-streams insert -r'.cdn.format=720p' '.cdn.ingestion-type=rtmp'
error: Found argument '.cdn.ingestion-type=rtmp', but youtube3 live-streams insert wasn't expecting any
```

**Comment by Byron** [comment]
Thanks for writing your journey down in all the detail ! It really helps to understand what you have been through, and hopefully helps to make things clearer in the future.

First of all, the example stated in the very beginning is something I don't find [in the CLI docs](http://byron.github.io/google-apis-rs/google_youtube3_cli/live-streams_insert/). What led to the conclusion this is a complete and valid example ?

The problems you are describing seem to stem from a lack of a complete example. You may find [one of my scripts useful](https://github.com/Byron/depot/blob/master/src/bash/upload-session-to-youtube.bash#L53), which is complete and working.

Please let me know if this is working for you.

**Comment by simcop2387** [comment]
so the first part comes from this in the cli docs

```
    -r .cdn    format=et
        The format of the video stream that you are sending to Youtube.
```

That's all on one line in the documentation, hence why i tried it like that.  It does seem to work with the video upload, but not with creating a live-stream matching how you're doing it gives the blank missing "required parameter missing" problem still.

**Comment by Byron** [comment]
Thanks for letting me know. Probably I will have to make clearer that potentially the entire request value will have to be specified, and that all mentioned fields are there just for the purpose of documentation.

It seems inevitable to consult the [official docs](https://developers.google.com/youtube/v3/live/docs/liveStreams/insert) on the method to find out which fields need to be set in particular. Unfortunately, this information is not available in the json files I use to generate everything, thus I can't let people know in my documentation.

In your case, these are the following:

----
![screen shot 2015-10-17 at 10 49 18](https://cloud.githubusercontent.com/assets/63622/10557859/c1555de6-74bc-11e5-9b6b-9b3f5fdbeb34.png)
----
If you provide all of them, it should be a valid call

**Comment by Byron** [comment]
Once it works for you, I'd be glad if you could post your findings here and close the issue.
Also note the new ticket to improve the docs - I'd consider any additional notes on how that could be achieved very valuable.
Thanks and cheers

**Comment by simcop2387** [comment]
Even with all of the listed required ones, it fails saying that there's a missing one.  

```
youtube3 --debug live-streams insert \
                        -r cdn \
                                format="720p" \
                                ingestion-type="rtmp" \
                           ..snippet \
                                title="Testing" \
                                description="One two three"
```

Watching what happens with --debug, the call is never actually made to the api (confirmed via wireshark also).  this is happening when parsing the CLI and not on the youtube side.  I've tried with both ingestion-type and ingestionType

**Comment by Byron** [comment]
Interesting ! I just pasted the code above into my shell, and it seemed to have worked right away. The live-stream seems to be hidden in the youtube interface, but the command executed happily:

```bash
➜  katars git:(master) youtube3 --debug live-streams insert \
>                         -r cdn \
>                                 format="720p" \
>                                 ingestion-type="rtmp" \
>                            ..snippet \
>                                 title="Testing" \
>
POST /youtube/v3/liveStreams?part=snippet%2Ccdn&alt=json HTTP/1.1
Host: www.googleapis.com
Authorization: Bearer SECRET
Content-Type: application/json
Content-Length: 78
User-Agent: google-api-rust-client/0.1.9

{"cdn":{"format":"720p","ingestionType":"rtmp"},"snippet":{"title":"Testing"}}HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Date: Sat, 17 Oct 2015 20:12:23 GMT
Vary: X-Origin
Content-Type: application/json; charset=UTF-8
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Alternate-Protocol: 443:quic,p=1
Alt-Svc: quic=":443"; p="1"; ma=604800
Accept-Ranges: none
Vary: Origin,Accept-Encoding
Transfer-Encoding: chunked

254
{
 "kind": "youtube#liveStream",
 "etag": "\"fpJ9onbY0Rl_LqYLG6rOCJ9h9N8/3SiezbvhS0DPDJri2o-5fVV7q7E\"",
 "id": "kn47As_FHFviIqEVAXx1vw1445112743033619",
 "snippet": {
  "publishedAt": "2015-10-17T20:12:23.000Z",
  "channelId": "UCkn47As_FHFviIqEVAXx1vw",
  "title": "Testing",
  "description": "",
  "isDefaultStream": false
 },
 "cdn": {
  "format": "720p",
  "ingestionType": "rtmp",
  "ingestionInfo": {
   "streamName": "Byronimo.y718-ac9d-1mu8-axzk",
   "ingestionAddress": "rtmp://a.rtmp.youtube.com/live2",
   "backupIngestionAddress": "rtmp://b.rtmp.youtube.com/live2?backup=1"
  }
 }
}

0

{
  "cdn": {
    "format": "720p",
    "ingestionInfo": {
      "backupIngestionAddress": "rtmp://b.rtmp.youtube.com/live2?backup=1",
      "ingestionAddress": "rtmp://a.rtmp.youtube.com/live2",
      "streamName": "Byronimo.y718-ac9d-1mu8-axzk"
    },
    "ingestionType": "rtmp"
  },
  "etag": "\"fpJ9onbY0Rl_LqYLG6rOCJ9h9N8/3SiezbvhS0DPDJri2o-5fVV7q7E\"",
  "id": "kn47As_FHFviIqEVAXx1vw1445112743033619",
  "kind": "youtube#liveStream",
  "snippet": {
    "channelId": "UCkn47As_FHFviIqEVAXx1vw",
    "description": "",
    "isDefaultStream": false,
    "publishedAt": "2015-10-17T20:12:23.000Z",
    "title": "Testing"
  }
}%
```

Which version of the CLI are you using ? Mine is `youtube3 0.3.2+20150706` (as per `youtube3 --version`)

**Comment by simcop2387** [comment]
youtube3 0.3.2+20150706 according to --version, commit from git is e4f89ce0c6c16480cccbe92aeaad55e3811beb83
rustc 1.5.0-dev (837840c61 2015-09-19)
cargo 0.6.0
and the cargo.lock
http://www.simcop2387.info/rustc/youtube3-cli.Cargo.lock

I am running on ARMv7 but I don't think that'll affect anything.  I'll update rustc and see if that affects anything too.

**Comment by Byron** [comment]
@simcop2387 Usually when the CLI parser is unhappy with the provided arguments, it will be very specific about what is missing. Do you have any local overrides which could cause outdated crate-versions to be compiled as dependencies ? Can you reproduce the issue on your own workstation, which probably is another platform ?

# Meta

These are the dependencies that were working for me:

```Toml
dependencies = [
 "clap 1.4.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "hyper 0.6.15 (registry+https://github.com/rust-lang/crates.io-index)",
 "mime 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "rustc-serialize 0.3.16 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde_json 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde_macros 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "strsim 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "yup-hyper-mock 1.3.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "yup-oauth2 0.5.2 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

**Comment by simcop2387** [comment]
No overrides at all.  Was a clean install.  I'm actually re-attempting this with the latest nightly hopefully tonight or tomorrow.  I was not able to reproduce it on my main workstation (x86-64), only on the raspberry pi 2 (armv7).  I strongly suspected it was some kind of weird version problem but didn't nail it down several months ago.  Will try to do better this time.

**Comment by Byron** [comment]
Please note that I just updated the code to work with Rust 1.6 and clap-rs. Maybe it changes things to the better.

**Comment by simcop2387** [comment]
Took a bit to get this compiled again (rust 1.6 and above needed more ram than the rpi2 has).  Seems to be working now, not sure what caused this to begin with but I've now got a working binary on ARM/Raspberry pi 2.  now to just figure out what series of magic i have to do to create and complete a live stream with it :)

**Comment by Byron** [comment]
Great to hear it works for you, so far :) !
Please keep me posted about any project-related issues you run into. For example, this week a patch landed that would fix the handling of all repeated parameters - this may or may not be relevant to you.

Authentication should also be working for you, as the Youtube API fortunately is allowed to use device authentication, which currently is the only supported mode of oauth2 I support.

Anyway, good luck ! Maybe I read about your project in a blog-post at some point in time :) !
