### ISSUE TITLE
CLI applications fail because of invalid access scopes

### ISSUE THREAD

**Issue by MrFloya** [Byron/google-apis-rs#130]
Hey Byron,

while playing around with the `drive2-cli`, I noticed even a basic `files list` does not work "out of the box". The API returns a `400 Bad Request` because the requested scope  `https://www.googleapis.com/auth/drive.apps.readonly` cannot be authorized. 

A quick google search revealed that [not all scopes are supported through the device flow](https://groups.google.com/d/msg/oauth2-dev/Rc4CJiykhk4/_kOk3D7JCygJ). This can easily confirmed by running `drive2 --scope https://docs.google.com/feeds files list` which succeeds.

I don't know how much you can do about this issue as this is apparently nowhere documented and the input .json files only provide minimal required scopes (as far as I remember?) but I thought I'd let you know anyway.

Cheers,
MrFloya

**Comment by Byron** [comment]
Thanks for letting me know indeed ! This finally resolves this long-standing question of mine.
This would mean that `yup-oauth2` should eventually implement a more common flow for authentication.

**Comment by programble** [comment]
I ran into this same issue, and ended up writing an OAuth2 client of my own: [inth-oauth2](https://crates.io/crates/inth-oauth2). It would be good for these libraries to have a more general interface for authentication, rather than being tied to `yup-oauth2`.

**Comment by Byron** [comment]
@programble Thanks for letting me know ! It's great to have a reference once I get around to updating `yup-oauth2` or integrating `int-oauth2` instead.

**Comment by Byron** [comment]
As of [version 0.6.0](https://github.com/Byron/yup-oauth2/blob/master/changelog.md#v060-2016-05-20), `yup-oauth2` has received a new oauth flow for installed apps. It's now the default, and allows all CLIs to work correctly now.
Plenty of fixes have been applied as well, so you should just be able to build the latest version locally, with `make drive3-cli-cargo ARGS=run`.
