### ISSUE TITLE
link to 404 on docs index

### ISSUE THREAD

**Issue by killercup** [Byron/google-apis-rs#14]
Hey, even though it's no longer Friday 13th, I just found a 404 on my first try to click on a link on http://byron.github.io/google-apis-rs/ ;)

The link for _qpxexpress v1_ is to `qpxexpress1/index.html`, which doesn't exist.

Looking at the gh-pages branch tells me the correct path is `qpxExpress1/index.html` (with a capitalized E).

**Comment by Byron** [comment]
Wow, lucky you ! This is the second case-sensitivity related bug for me in two days :) ! OSX seems to attract these ... .
Thanks for posting, this one will be fixed tomorrow.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](http://youtu.be/OHwZsqHfosg).

**Comment by Byron** [comment]
This one definitely works now: http://byron.github.io/google-apis-rs/qpxexpress1/index.html .

**Comment by killercup** [comment]
Yay, lower case everywhere! It was quite cool to watch you solve this. I feel your pain with case-insensitivity on OS X, this has cost me a few hours of despair as well… (Once, I even tried to change the mode in HFS – it wasn't pretty.)





Viele Grüße aus Köln!
