### ISSUE TITLE
Compatibility with Async Hyper

### ISSUE THREAD

**Issue by indiv0** [Byron/google-apis-rs#152]
As of https://github.com/hyperium/hyper/commit/d35992d0198d733c251e133ecc35f2bca8540d96, hyper is an async library. Will `google-apis-rs` be updating to support async Hyper IO?

**Comment by Byron** [comment]
I currently have no  plans to support the Async API, primarily as I have no use-case for it. If you use the google-api's for one of your project and would know such a use-case, we could talk about how to get it implemented, maybe via a feature-flag (one generates with the sync-version, one provides an async-API).

As this might answer your question, I am closing this issue - feel free to place more comments though in case you want to reply.
