### ISSUE TITLE
Google speech API

### ISSUE THREAD

**Issue by dirvine** [Byron/google-apis-rs#156]
Hi, brilliant work here. I wonder are there plans to add the google speech API ? If not is there a way to add this myself or is it best to write from scratch for that one? 

Thanks again

**Comment by Byron** [comment]
Sorry for not replying - this issue went past me somehow.
Is there still interest?

Currently the speech API is blacklisted as there was an issue with the generated code - usually it's fixable, or might be fixed already with the latest version.

Just let me know and I will give it another shot.

**Comment by Byron** [comment]
The Speech API is available by now.
