### ISSUE TITLE
Update to serde 0.9

### ISSUE THREAD

**Issue by dtolnay** [Byron/google-apis-rs#161]
Check out the release notes: https://github.com/serde-rs/serde/releases/tag/v0.9.0

**Comment by Byron** [comment]
Thanks for the heads up!
How do you think the project will benefit?
Is it about macros 1.1, and getting rid of build scripts? Because that I would indeed love to do:) !

**Comment by dtolnay** [comment]
It is about macros 1.1 and getting rid of build scripts.

**Comment by Byron** [comment]
Great, will do and re-release on Feb. 5th.

**Comment by Byron** [comment]
This is a related PR, just for completeness: https://github.com/dermesser/yup-oauth2/pull/54

**Comment by Byron** [comment]
I am publishing new versions right now, which will work with the latest yup-oauth2 and require serde-0.9.
