### ISSUE TITLE
remove "with-serde-codegen" feature for yup-oauth2 from generated Cargo.toml

### ISSUE THREAD

**Issue by dermesser** [Byron/google-apis-rs#162]
It causes programs pulling in yup-oauth2 and a google API crate to fail compilation:

```
error: Package `yup-oauth2 v1.0.4` does not have these features: `with-serde-codegen`
```

I'm not too familiar with features, so I don't feel qualified making a PR; it should be a one- or two-line change however.

**Comment by Byron** [comment]
I am working on this already, but didn't push. Fix will land tomorrow.
Lesson learned: use major releases generously.

**Comment by dermesser** [comment]
sorry, I didn't mean to be pushy. I thought the same about major releases :-)

**Comment by Byron** [comment]
No worries, I am just on the phone 📱

**Comment by Byron** [comment]
I am currently publishing new versions! Manual tests show that it works just fine, using rust-tls for the connection.
Now I am so looking forward to an openssl free authentication, and building the APIs will be so much  easier :).
