### ISSUE TITLE
Gmail - messages_list returns "Bad Request"

### ISSUE THREAD

**Issue by e-oz** [Byron/google-apis-rs#163]
Pretty simple code to reproduce, part after authenticator creation:

```rs
  let result = hub.users().messages_list("me")
    .max_results(5)
    .include_spam_trash(false)
    .doit();
  match result {
    Err(e) => { println!("Error: {:?}", e) },
    Ok(res) => println!("Success: {:?}", res),
  }
```

result:
```
Error: BadRequest(ErrorResponse { error: ServerError { errors: [ServerMessage { domain: "global", reason: "failedPrecondition", message: "Bad Request", location_type: None, location: None }], code: 400, message: "Bad Request" } })
```
---
Version in Cargo.toml: `google-gmail1 = "1.0.4+20161206"`
Authentication: `ServiceAccountAccess` (works fine)

**Comment by e-oz** [comment]
I found an issue - "sub" is required to read emails.
Please consider PR: https://github.com/dermesser/yup-oauth2/pull/58

**Comment by Byron** [comment]
Thanks for pointing this out and for the fix! I have had a look at the changes, and they seemed fine to me, but I will wait for the expertise of @dermesser and wait for the merge.
However, is it correct that this error only occours when using a service account? The CLI should work fine as it uses a user-based account by default.

**Comment by e-oz** [comment]
Yes, this is only useful for service accounts, because with usual oauth2-authentication we don't need to impersonate user.
This code doesn't bring breaking changes, just one new constructor.

**Comment by Byron** [comment]
As the authenticator used is entirely dependent on yup-outh, and the choice of version is entirely controlled by the user of the library, I am closing this issue just not to distract from getting the PR merged.
I don't think anything can or has to be done on the side of google-apis-rs.
If you feel differently, please let me know in a comment what exactly you would require here.
