### ISSUE TITLE
sheets api generation fails

### ISSUE THREAD

**Issue by bbigras** [Byron/google-apis-rs#164]
I'm not sure how to build the sheets api. There seems to be [a json file](https://raw.githubusercontent.com/Byron/google-apis-rs/06caa1de02a9a6b8b8d843bb45bad02efd7a9790/etc/api/sheets/v4/sheets-api.json) in the repo but I don't see the sheets api when I do `make help-api`.

**Comment by Byron** [comment]
Sorry for the late reply.
The sheets-api is [blacklisted](https://github.com/Byron/google-apis-rs/blob/c4e363d94ce1715f3ecfe6fd6ee56b93c670bfb2/etc/api/shared.yaml#L28), which is done when some types don't pan out and thus the Rust code cannot compile. This is something that can be fixed usually - I think there are facilities for this - but I don't invest the time unless I need the API myself.

I suggest you to remove the entry, run make, and see what happens then. You could also run `make update-json` to fetch the latest version of the API, and possibly it fixes itself.

Please let me know if there are other issues or further questions, and feel free to make a PR in case you get a positive result.

**Comment by MTRNord** [comment]
Even if I am not the one who asked but for me it fails with:

```
Generating sheets4


Traceback (most recent call last):
  File "etc/bin/mako-render", line 324, in cmdline
    result = post_processor(template.render(**data_converted), output_file)
  File "/home/marcel/google-apis-rs/.pyenv-Linux/lib/python2.7/site-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/marcel/google-apis-rs/.pyenv-Linux/lib/python2.7/site-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/marcel/google-apis-rs/.pyenv-Linux/lib/python2.7/site-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/marcel/google-apis-rs/.pyenv-Linux/lib/python2.7/site-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "src/mako/api/README.md.mako", line 1, in render_body
    <%
  File "/home/marcel/google-apis-rs/src/mako/lib/util.py", line 772, in new_context
    _sta_map, _fqan_map = build_activity_mappings(data_source)
  File "/home/marcel/google-apis-rs/src/mako/lib/util.py", line 656, in build_activity_mappings
    build_activity_mappings(a.resources, res, fqan)
  File "/home/marcel/google-apis-rs/src/mako/lib/util.py", line 654, in build_activity_mappings
    for a in activities.values():
TypeError: 'DictObject' object is not callable
make: *** [.api.deps:3268: gen/sheets4/.timestamp] Fehler 1
```

**Comment by Byron** [comment]
I think it should be possible to fix the generator to deal with this particular API specification.

**Comment by toulouse** [comment]
I'd really like it if the sheets4 API could be fixed and whitelisted again, if possible. To that end, I did a bit to hunt it down, but this isn't really my forte.

---


To debug this, I ran `make -n sheets4` to do a dry run of make to get the Python command to run:
```
% make -n sheets4
echo Generating sheets4
PYTHONPATH=src/mako/lib:src/mako/api/lib .pyenv-Darwin/bin/python etc/bin/mako-render --template-dir '.' -io src/mako/api/README.md.mako=gen/sheets4//README.md src/mako/api/../LICENSE.md.mako=gen/sheets4//LICENSE.md src/mako/api/../Cargo.toml.mako=gen/sheets4//Cargo.toml src/mako/api/lib.rs.mako=gen/sheets4/src/lib.rs  --data-files etc/api/sheets/v4/sheets-api.json etc/api/shared.yaml etc/api/type-api.yaml
touch gen/sheets4/.timestamp
echo "// COPY OF 'src/rust/api/cmn.rs'"  > gen/sheets4/src/cmn.rs
echo "// DO NOT EDIT"  >> gen/sheets4/src/cmn.rs
cat src/rust/api/cmn.rs >> gen/sheets4/src/cmn.rs
```
Then I ran this to get into the debugger:
```
PYTHONPATH=src/mako/lib:src/mako/api/lib .pyenv-Darwin/bin/python -m pdb etc/bin/mako-render --template-dir '.' -io src/mako/api/README.md.mako=gen/sheets4//README.md src/mako/api/../LICENSE.md.mako=gen/sheets4//LICENSE.md src/mako/api/../Cargo.toml.mako=gen/sheets4//Cargo.toml src/mako/api/lib.rs.mako=gen/sheets4/src/lib.rs  --data-files etc/api/sheets/v4/sheets-api.json etc/api/shared.yaml etc/api/type-api.yaml
```
Note the `-m pdb` addition to start with the python debugger.
Then I set breakpoints at these lines (you'll want to feed the absolute path when you set it with `b /path/to/file:line`):

* `google-apis-rs/.pyenv-Darwin/lib/python2.7/site-packages/mako/runtime.py:899`
* `google-apis-rs/src/mako/lib/util.py:772`
* `google-apis-rs/src/mako/lib/util.py:656`

As far as I can tell, `google-apis-rs/src/mako/api/README.md.mako` is failing to render on the recursive invocation of `build_activity_mappings`.

The first time, `activities.values` in `for a in activities.values():` has type "instancemethod", which if called, produces a dict; the second time, it is a straight-up dict:
```
(Pdb) b /(...)/google-apis-rs/src/mako/lib/util.py:654
Breakpoint 1 at /(...)/google-apis-rs/src/mako/lib/util.py:654
(Pdb) c
> /(...)/google-apis-rs/src/mako/lib/util.py(654)build_activity_mappings()
-> for a in activities.values():
(Pdb) type(activities.values)
<type 'instancemethod'>
(Pdb) c
> /(...)/src/mako/lib/util.py(654)build_activity_mappings()
-> for a in activities.values():
(Pdb) type(activities.values)
<class '__main__.DictObject'>
```
In the first call, activities.values() has one element, so it's probably to say that there's something wrong with `activities.values()[0].resources.values` not being a function (that returns a dict), for some reason.

If I delete all text in `README.md.mako`, the same error happens in the same sort of code, except in `src/mako/api/lib.rs.mako`.

So, the problematic lines in both would appear to be this:
```
c = new_context(schemas, resources, context.get('methods'))
```
I don't know much about that, and I've done as much as I can dedicate time to, but there you go.

**Comment by toulouse** [comment]
Looks like someone's just put up a pull request! #183

**Comment by Byron** [comment]
Indeed! It's like a new-years gift :).
Here is the published crate: https://crates.io/crates/google-sheets4-cli .

**Comment by karlek** [comment]
The documentation is missing for `google-sheets4-cli`: https://byron.github.io/google-apis-rs/google_sheets4_cli

**Comment by Byron** [comment]
Sorry, I forgot to update the pages. It's there now :).
