### ISSUE TITLE
How to use strongly type data with "insert_all" method for bigquery

### ISSUE THREAD

**Issue by opensourcegeek** [Byron/google-apis-rs#165]
Thanks for this library - it has helped me move some of my work to Rust in a much easier way.

I'm trying to follow the type signature in order to do a insert_all request to bigquery. I need to create a request of type TableDataInsertAllRequest, which has rows that I could set,  Option<Vec<TableDataInsertAllRequestRows>>. However in order to set rows property of  TableDataInsertAllRequestRows I need Option<JsonObject> which is where I'm getting confused. 

is JsonObject a tuple struct here? It wraps a HashMap<String, JsonValue>, how do I create it from my custom structs please? Why does rows property of TableDataInsertAllRequestRows not take Vec< JsonValue>, why do we need this intermediate wrapper types? Any help would be very helpful - thanks.

**Comment by Byron** [comment]
I am not quite sure what the issue is - can you please provide links to the documentation, and make clear what your source data looks like?
To me it seems the API wants a `Vec` of something, whereas you have a `JsonValue`, and you are wondering how to perform the conversion.

**Comment by opensourcegeek** [comment]
I'd moved away from using this library at that point in time and started using REST API directly as I couldn't get my head around generated APIs. 

To be fair, I didn't spend an awful lot of time to understand how the API is setup. Just looking at it again now,

```rust
pub struct TableDataInsertAllRequestRows {
    /// [Optional] A unique ID for each row. BigQuery uses this property to detect duplicate insertion requests on a best-effort basis.
    #[serde(rename="insertId")]
    pub insert_id: Option<String>,
    /// [Required] A JSON object that contains a row of data. The object's properties and values must match the destination table's schema.
    pub json: Option<JsonObject>,
}

pub struct JsonObject(Option<HashMap<String, JsonValue>>);
```
I think I was referring to json property here which takes an optional `JsonObject` and that object in turn wraps an option `HashMap` of string to `JsonValue`. This is where I got confused as my data structure already was in the shape I needed it to be, so I gave up and just pushed the data directly using REST API at that point. 

My data structure was something like this for example,

```rust
#[derive(Serialize)]
pub struct MyData {
   name: String,
   dateTime: u64,
   places: Vec<Place>
}
```
How would you go about setting `TableDataInsertAllRequestRows`s json property with a `Vec<MyData>`?

I appreciate time and effort you have put into this library, I'm mentioning my pain points so that you can make this library much more accessible for new comers like me.

**Comment by Byron** [comment]
Thanks for taking the time to elaborate! I am sure this issue will help to make the next iteration of these bindings better, and easier to use!
For now I don't even know what to say here as these datatypes are so complex and the APIs so unique that I literally have no idea what the generator is doing, and if it really makes sense or not.
My only test-library that I wanted working back in the days was the one to interact with YouTube.

**Comment by zeapo** [comment]
I know it's late, but I was faced by this issue. The solution I found was to go through `serde`:

```rust
    #[derive(Serialize)]
    struct Example {
        foo: String,
        bar: String
    }

    let json_value = serde_json::to_value(Example {
        foo: "foobar".to_string(),
        bar: "barfoo".to_string(),
    }).unwrap();

    // you can add here the insertId
    let val = serde_json::json!({ "json": json_value });
    let isn: TableDataInsertAllRequestRows = from_value(val).unwrap();
    insert.rows = Some(vec![isn]);

    let result = hub.tabledata().insert_all(insert, "proj", "ds", "table").doit(); 
```

**Comment by Byron** [comment]
@zeapo Thanks a lot for chiming in!
I think this is what @opensourcegeek would have needed to make this API work for them! Maybe the answer helps in future :).

**To sum it up**: Strongly typed data cannot be used _directly_ with `TableDataInsertAllRequestRows`, but it's possible to transform strongly typed data into the format required as shown in the example above.
