### ISSUE TITLE
Malformed documentation

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Byron/google-apis-rs#166]
It looks like the html for http://byron.github.io/google-apis-rs/ got a little messed up. I've attached screenshots of the offending sections.

Would it be better to use a table instead of a bunch of spans and `<br>` tags? If you can point me at whatever file you're using as the page template, I'd be happy to fix it up.

![screenshot_2017-03-31_211357](https://cloud.githubusercontent.com/assets/17380079/24551936/26ca2c1e-1657-11e7-8f2a-857eb5f4860d.png)
![screenshot_2017-03-31_211413](https://cloud.githubusercontent.com/assets/17380079/24551937/26ca947e-1657-11e7-9fde-51db7208da53.png)

**Comment by Byron** [comment]
Quick reply from mobile: thanks for offering your help :) - I will gladly
merge the fix!
You can find the source in "index.html.mako", and build it using 'make
docs' or something like it. Make also knows how to build just the output
file index.html, but I don't know by heart where it is.
