### ISSUE TITLE
Youtube doc example doesn't work (hyper HTTPS problem)

### ISSUE THREAD

**Issue by FliegendeWurst** [Byron/google-apis-rs#169]
The [example](https://docs.rs/google-youtube3/1.0.4+20161202/google_youtube3/struct.YouTube.html).
```rust
MissingToken(StringError { error: "Invalid scheme for Http" })
```
This happens because hyper doesn't support HTTPS out of the box anymore. Perhaps a note about hyper-native-tls (or hyper-rustls) should be added to the docs?

**Comment by Byron** [comment]
@FliegendeWurst Thanks for letting me know. I will update the documentation and publish the latest version of the crates in the process.
