### ISSUE TITLE
google-gmail1-cli 1.0.5+20170510: 401 deleted_client error

### ISSUE THREAD

**Issue by aetherknight** [Byron/google-apis-rs#170]
I installed google-gmail1-cli to try and use it to explore Google's GMail API. However, when I try to use the tool and perform the OAUTH flow, I get an error from Google indicating that the client has been deleted.

Command line output:

```
$ gmail1 -V
gmail1 1.0.5+20170510

$ gmail1 users settings-filters-list me
Please direct your browser to https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/gmail.readonly&redirect_uri=http://localhost:54324&response_type=code&client_id=620010449518-9ngf7o4dhs0dka470npqvor6dc5lqb9b.apps.googleusercontent.com and follow the instructions displayed there.
```

When I open the link, the error I get is:

<img width="646" alt="google-401-deleted-client" src="https://cloud.githubusercontent.com/assets/62613/26764926/d5547bda-4925-11e7-948f-ddf2f19bb144.png">

After looking at the command line options and glancing at the generated source code for the CLI tool, it looks to me like the app ID is hard-coded into the CLI tool, so I don't think I can work around this in the with just configuration.

**Comment by greglearns** [comment]
+1 on version
gmail1 -V
gmail1 1.0.7+20171128

**Comment by Byron** [comment]
Most applications come with a default client, which was created by me, but will be purged by google from time to time.

The documentation of the CLI [suggests a workaround](http://byron.github.io/google-apis-rs/google_gmail1_cli/index.html#application-secrets), does that not work you?

**Comment by Byron** [comment]
@aetherknight Sorry for replying so late! Somehow the entire issue went past me, which is particularly annoying as a 'fix' is easy to achieve.

**Comment by aetherknight** [comment]
@Byron I followed the instructions in the documentation to create my own OAUTH client credentials, and that worked. Thanks!

**Comment by greglearns** [comment]
Just confirming that these are the right steps:
1) enable gmail in the Google API Console
2) using the "credentials" menu option, then selecting "Create Credentials" dropdown, select the "OAuth client ID", then select the "Web" option, then, under the "Authorized redirect URIs", enter "http://localhost:54324", then save it, and download it to ~/.google-service-cli/gmail1-secret.json", then edit that json file, changing `'"web":{` to `"web":null,"installed":{`, saving that, and then things work.
Is this correct?

**Comment by aetherknight** [comment]
@greglearns I used the "Help Me Choose" option, and after answering the questions the Google developer console created an OAUTH client ID of type "other" instead of "web". I then didn't have to deal with setting up an authorized redirect URI.

**Comment by greglearns** [comment]
Ok, that worked. The directions are:

1) enable gmail in the Google API Console
2) using the "credentials" menu option, then selecting "Create Credentials" dropdown, select the "OAuth client ID", then select the "Other" option, then, save that, and then download the credentials, saving them to ~/.google-service-cli/gmail1-secret.json", and then things work.

Thank you for your help.

**Comment by greglearns** [comment]
On a different note, using gmail1 to get a draft email
`gmail1 users drafts-get user@domain.com 1546072694021605315`

returns multipart encoded values instead of the actual text. Do you recommend a good parser for reading the JSON results from `gmail1`?
