### ISSUE TITLE
Generate pre-signed URLs?

### ISSUE THREAD

**Issue by thedodd** [Byron/google-apis-rs#178]
Pretty impressive project here. I am looking for a convenience function for generating pre-signed URLs for access to objects in storage.

Any ideas on that?

**Comment by Byron** [comment]
For reference, here is the [documentation on pre-signed urls](https://cloud.google.com/storage/docs/access-control/signed-urls).

Despite me having never used this feature and just having looked it up, I believe you should be able to use the app-identity API to do this. However, I didn’t find it in the [API-list](http://byron.github.io/google-apis-rs/) of this project, so getting it might be a manual call away.

Also I don’t know how they are actually used. I hope that answers your question.

**Comment by mwilliammyers** [comment]
Not sure if you or anyone is still looking for this but you are probably looking for the `*sign_blob` methods in the [iam](https://docs.rs/google-iam1/1.0.8+20181005/google_iam1/struct.ProjectServiceAccountSignBlobCall.html) crate or the [iamcredentials](https://docs.rs/google-iamcredentials1/1.0.8+20181004/google_iamcredentials1/struct.ProjectServiceAccountSignBlobCall.html) crate. Not sure what the difference is between those two APIs and I haven't used either one but I have used the corresponding methods in other API libraries to do what you want.
