### ISSUE TITLE
google-drive3 1.0.6+20170512 is not downloadable

### ISSUE THREAD

**Issue by icepuma** [Byron/google-apis-rs#179]
Setup to reproduce:

My minimal `Cargo.toml`:
```rust
[package]
name = "google-drive-cleaner"
version = "0.0.1"
authors = ["icepuma"]

[dependencies]
google-drive3 = "1.0.6+20170915"
```
The outcome after running `cargo build`:
```bash
Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading google-drive3 v1.0.6+20170512
error: unable to get packages from source

Caused by:
  failed to verify the checksum of `google-drive3 v1.0.6+20170512`
```

**Comment by FliegendeWurst** [comment]
This also happens with google-youtube3.

**Comment by dweidenfeld** [comment]
The problem is, that the semver syntax is wrong.
It must be `1.0.6-20170915` instead of `1.0.6+20170915`.

The plus sign indicates no new version, so it actually compares two different versions with each other and the checksum comparison fails.

**Comment by marcaddeo** [comment]
Is there a workaround for this?

**Comment by Byron** [comment]
The only one I know is to ask Alex Chrichton to fix it.
It’s a know bug in crates.io, maybe some sort of race condition.
I could also just republish everything, but don’t know when I get around to
that.

**Comment by FliegendeWurst** [comment]
Editing the Cargo.lock file works for me

**Comment by dweidenfeld** [comment]
@FliegendeWurst what did you enter?

**Comment by neoeinstein** [comment]
Manually changing erroring date to the newer date (for Google PubSub it was 20170502 -> 20170829) worked for me. There are at least three locations in the `Cargo.lock` file that needed that date changed.

```diff
- "google-pubsub1 1.0.6+20170502 (registry+https://github.com/rust-lang/crates.io-index)",
+ "google-pubsub1 1.0.6+20170829 (registry+https://github.com/rust-lang/crates.io-index)",
```

**Comment by sourcepirate** [comment]
How do we get around this problem ?

**Comment by skyne98** [comment]
Any non-hacky solutions available?

**Comment by NathanHowell** [comment]
Pinning an older version seems to work okay, note the equals sign:

```
google-storage1 = "=1.0.5+20170504"
```

**Comment by Byron** [comment]
I was trying to just create a new release in the hopes of fixing the problem, but see this issue re-occurring with a huge amount of crates.
The next step for me is to escalate this to the crates.io maintainers.

**Comment by Byron** [comment]
Aaaah, right, as noted by an earlier comment: https://github.com/Byron/google-apis-rs/issues/179#issuecomment-341649344 
I did not increment the main version, just the version after the +sign.
I will just try again :)!

**Comment by Byron** [comment]
The latest release should fix this issue, but please let me know if it is still not working correctly for you.
