### ISSUE TITLE
Verify Id token in backend

### ISSUE THREAD

**Issue by franklinyu** [Byron/google-apis-rs#182]
This is a feature request.

I'm trying to write server in Rust that [verifies the Id token I receive during Google Sign In](https://developers.google.com/identity/sign-in/web/backend-auth). The flow is different from OAuth, but I believe the token is a JSON Web Signature signed by Google, with user's information as payload, so it should be easy to integrate.

**Comment by Byron** [comment]
Sorry for the late reply.
I wonder if the [`service account`](https://docs.rs/yup-oauth2/1.0.6/yup_oauth2/) flow is for you and already supported. It's just that I remember the author of `yup-oauth2` implement it for exactly that reason, but maybe he has been using it outside of the libraries provided by `google-apis-rs`.

If you think this is something this library, as a client, should do, can you be more specific about how that would look like, providing an example that makes it clear to the potential implementer?
Thank you

**Comment by franklinyu** [comment]
No, service account is for "server to server" flow. In that workflow, I build an application to retrieve my own data, instead of my user's data. For example, my Rust application only sees my Google Drive, my contacts, and my mails. No user involved.

### what is Google Sign In

The *Google Sign In* is an improvement (that is, *replacement*) over three-leg OAuth 2.0, although the JavaScript package is (confusingly) named `auth2`. In traditional three-leg OAuth 2.0, user is redirected from my application to Google, with parameters telling Google my identity (and `state` to prevent CSRF). After user sign in, he/she is redirected back to my application, with the user's credential, so that my application can access user's data on Google services. My application is somewhat special, in that it only need basic identity information, instead of further data such as Google Drive or Gmail, so it's more about authentication instead of authorization.

*Google Sign In* is a new framework designed to specifically improve this "authentication without authorization" scenario. In this new workflow, no redirection is involved (so no more CSRF!). My front-end JavaScript receives a token by some magic in Google library, and it sends the token back to my Rust backend (typically through AJAX). Then my backend does roughly (sorry I'm still learning Rust):

```
use auth2::Authenticator;

let auth = Authenticator::new();
let token = request.get_token();
match auth.verify(&token) {
    Ok(identity) => println!("user name: {}", identity.name),
    Err(reason) => println!("invalid Id: {}", reason),
}
```

where `.verify()` should parse and verify the token (actually a JSON Web Signature, so I think [biscuit](https://lawliet89.github.io/biscuit/biscuit/index.html) would help).

### note

 1. I'm not sure whether this function belongs to this library, since it does not query a real Google API, except downloading the certificates (JSON Web Key or PEM format). Ideally it caches the certificates, but the certificates does expire for whatever (maybe security?) reason.
 2. I can help implementing this. I'm not good at Rust, but I know how to do it in other languages, like Ruby, Python and Java.

**Comment by Byron** [comment]
@franklinyu Thanks a lot for the detailed explanation. To me this seems to be a better fit for a separate crate even, as it does not appear to be oauth2, nor can it be used for any google API that this repository provides.
Do you think my conclusion makes sense?

**Comment by franklinyu** [comment]
Yes, there is no consensus in other official Google SDK that I know of.

Actually I created this issue wondering whether this feature has already been included, but buried deep somewhere. Now that it is not included, there's good reason not to. Even if it was included, I would suggest extracting it out into a separate library.

I may even build such a library myself...

**Comment by seenickcode** [comment]
@FranklinYu hello, I have the exact same use case. I just posted this [SO question](https://stackoverflow.com/questions/67259780/validating-google-sign-in-id-token-in-rust) here before I stumbled across this post. 

What did you end up doing in your case?

**Comment by chikko80** [comment]
Any news on this?

**Comment by Byron** [comment]
I don't know to what extend it's relevant here, but a related improvement in the recent addition of the [`GetToken` trait](https://github.com/Byron/google-apis-rs/blob/main/google-apis-common/src/auth.rs#L85) which allows the application take full ownership over how authentication is done. The crates produced in this repository only care about passing a token with each request they believe needs auth*.

My feeling though is that this issue isn't about using a Google API, unless a `google-signin` API exists which isn't the case here, but there is [a crate available](https://crates.io/crates/google-signin) on crates.io.
