### ISSUE TITLE
migrate to use hyper-(native-)?-tls

### ISSUE THREAD

**Issue by ignatenkobrain** [Byron/google-apis-rs#194]
We package google-drive3 crate for Fedora and we want to avoid packaging `ring` because we don't want to have multiple different crypto libraries.

It would be very nice to switch to use hyper-native-tls for the time being (until you port to hyper 0.12) and after that to use hyper-tls.

**Comment by Byron** [comment]
Thanks for letting me know! Once `yup-oauth2` has attempted the move, I would be willing to try the same for this library.
Right now I am afraid of opening up a rabbit hole :), yet acknowledge I might not be that bad after all.

**Comment by ignatenkobrain** [comment]
So yup-oauth2 has switched ;)

**Comment by ignatenkobrain** [comment]
I will send a patch.

**Comment by Byron** [comment]
@ignatenkobrain Thank you! It's much appreciated. I see some maintenance time coming up for this project soon, too.

**Comment by Byron** [comment]
This is done with the latest published version of the crates: v2.0
