### ISSUE TITLE
Rust google-bigquery2 invalid sequence

### ISSUE THREAD

**Issue by paperplanes53** [Byron/google-apis-rs#196]
I am unable to query more than one Record in a schema. My error includes my BigQuery query data then Error("invalid type: sequence, expected a string". 

Example Schema: 
extra_count [Integer, Nullable]
people [Record, Nullable] 
people.count [Integer, Nullable]
people.famous[String, Nullable]
people.things [Integer, Nullable]
house [Record, Nullable]
house.kitchen [String]
house.bathroom[String]

I tried unnesting the fields and yet queries including fields from more than one record fail. However, these queries work on Google BigQuery cloud queries. 

For example, the following would fail in my Rust code but not the cloud:

SELECT people.count, people.famous, extra_count, house.kitchen FROM database.table WHERE ((people.count BETWEEN 2 AND 5) OR  (people.things BETWEEN 1 AND 12)) AND  (extra_count BETWEEN 0 AND 19)

**Comment by Byron** [comment]
Thanks for letting us know! As it stands, the current implementation is frozen and won't change except for the occasional 'automated update with `make update-json`' or merging PRs.
However, if (or when) the next iteration of it starts getting implemented to support the async world and learn from all limitations of the past, this issue will be taken into consideration to assure we can handle this properly.

**Comment by Byron** [comment]
Please note that as the issue stands, I would not be able to reproduce it just because I have no inherent knowledge about this particular API. This might be a problem when it is about adding support later.

**Comment by Byron** [comment]
Thanks again for posting your research here! As I believe @TheBiggerGuy  is currently diving into the type inference system, maybe being aware of the solution here can prove useful :).

**Comment by TheBiggerGuy** [comment]
Hi, I have now a request to include testing of the Google schema to Rust type code #210.

I would like the project to think carefully if it wants to expose a third party lib as a return type. I am not against it but it does more tightly link serde with google-api-*

Independent of the outcome it sounds like a great candidate for a test.

**Comment by Byron** [comment]
@TheBiggerGuy Back in the days when this library was created, relying on serde was much more of a risk than it is now. Today it's the defacto standard for serialization and deserialization in Rust, and I would trust that it remains that way.
As all types already use serde annotations and we rely heavily on using serde, I think that using serde types directly to fix bugs is a fair trade.

If some values indeed use the '`any`' type, to me it seems using `serde_json::Value` is the best way of representing it.

@TheBiggerGuy Maybe there are other options whose benefits outweigh the ones mentioned here.
