### ISSUE TITLE
Allow Local Discovery Document for generation

### ISSUE THREAD

**Issue by mpiannucci** [Byron/google-apis-rs#197]
In other languages, I can generate a client for my own APIs running on Google App Engine using a discovery document generated from them. This is the same document used to describe the google apis available here. It would be awesome if I could skip the download of the default apis and just feed a json file in the same format instead.

**Comment by mpiannucci** [comment]
To follow up, I was able to get this to work by doing the following:

* Creating a folder in `etc/api` with the name of the api and a sub folder with the version
* add the discovery doc to the version folder, named exactly with `[myservice]-api.json`
* add the service name and version to /etc/apis/api-list.yaml
* run make and the service shows up with all of the other options

Not sure if I should close this or not becasue it might be useful to add a feature to make this documented or something.

**Comment by Byron** [comment]
Indeed, this is how it can be done. In the end, the `api-list.yaml` file is what matters when executing make to regenerate all the project-automation. 
Something else that is soon possible thanks to @TheBiggerGuy is the addition of manually added libraries like so, see the #201 PR.

**Comment by Byron** [comment]
There is now a new version of the generator, in case it matters; http://github.com/google-apis-rs/generator
