### ISSUE TITLE
Add photos API

### ISSUE THREAD

**Issue by emosenkis** [Byron/google-apis-rs#198]

**Comment by TheBiggerGuy** [comment]
A working version of the Google Photos API (photoslibrary ver 1) can be found by using
```toml
google-photoslibrary1 = { git = "https://github.com/TheBiggerGuy/google-apis-rs", branch = "photoslibrary_str_int" }
```
I have been using it for a week now and it seems to be working fine. Until #201 is merged please feel free to use my branch.
