### ISSUE TITLE
Blogger API seems to be missing setters for actual post content

### ISSUE THREAD

**Issue by emosenkis** [Byron/google-apis-rs#199]
I don't see setters on the insert, update, and patch methods that set the post content, title, etc.

**Comment by Byron** [comment]
To me it looks like these values are passed as part of the [`Post`](https://docs.rs/google-blogger3/1.0.7+20150422/google_blogger3/struct.Post.html) structure. From there you find links to all the methods that take it as input or output.
Hope that helps.

Please note I am closing this issue just to mark it done for myself, please be invited to add follow-up questions as you see fit.
