### ISSUE TITLE
upload_resumable requires content length

### ISSUE THREAD

**Issue by Licenser** [Byron/google-apis-rs#216]
based on the API spec the resumable upload does not require a pre-defined content length, this allows streaming data into a GCS object.

Under the hood, it looks like the [upload function](https://github.com/Byron/google-apis-rs/blob/master/src/rust/api/cmn.rs#L664) is shared between resumable and simple uploads this causes it to try to get the total length for the object and fail for an unknown sized object.

**Comment by Byron** [comment]
Thanks for bringing this up! Right now this appears to be an API limitation, which does indeed require the content length to be known in advance.

**Comment by Byron** [comment]
Now that this repository entered _maintenance mode_ it's unlikely this issue will be fixed outside of contributions. However, maybe [one of the next-generation API generators](https://github.com/google-apis-rs)) will work for this usecase.
