### ISSUE TITLE
Difficulties debugging  HTTP failures with `Delegate`

### ISSUE THREAD

**Issue by cpick** [Byron/google-apis-rs#218]
When I was debugging #217 I ran into a few issues using `Delegate`:
1. None of the various lib.rs files for each crate re-export cmn.rs' either `JsonServerError` or `ServerError`.  This prevents users from implementing `Delegate::http_failure()` since it accepts those structs as parameters.
1. Some APIs (like google_firestore1_beta1's `hub.projects().databases_documents_commit()`) return errors that don't parse cleanly into either `JsonServerError` or `ServerError` so there's no way to access/print the body of the error's response.
1. Not all 400 errors parse cleanly into `ErrorResponse` so the `Errror::Failure` variant was being returned from `doit()` (as opposed to the `Error::BadRequest` variant) which is why I was going down the `Delegate` path in the first place.

1) should be easy to fix: (I can submit a PR re-exporting those two types if that sounds reasonable).  2) is a bit trickier.  When debugging my fork I changed `http_failure()`s parameter to just be a `serde_json::Value` so I could print *something* and that worked well enough (I was trying to read an error message and didn't need the extra structure).  Fixing 3) would have eliminated the need to do 2).  I can provide some example error body responses if that's helpful.

I'm happy to submit patches if there are any thoughts about how to improve things here.
Thanks for such a great useful project, it's helped immensely.

**Comment by Byron** [comment]
Thanks a lot for bringing this up!

#### About 1)

This is an oversight. Now every library is re-exporting everything in `cmn.rs`.

#### About everything else :)

I am happy to merge patches that worked for you. If these are breaking changes, I am happy to create new major version releases if the solution improves life for all users of the library.

And... sorry for the late reply!

**Comment by binarybana** [comment]
I'll leave a concrete case story about this here in case it is helpful (we might be able to come back and help here as well, so I wanted to leave a bread trail).

From GCP’s [API explorer](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.topics/publish) I get the following error when trying to publish a pubsub message with an empty string:
```{
  "error": {
    "code": 400,
    "message": "At least one permission must be specified.",
    "status": "INVALID_ARGUMENT"
  }
}```
Whereas from the GCP crate, all I’ve managed to get out was:
```Err(ErrorMessage { msg: "Failure(Response { status: BadRequest, headers: Headers { ... }, version: Http11, url: \"https://pubsub.googleapis.com/v1/projects/octomizer/topics/test-topic:publish?alt=json\", status_raw: RawStatus(400, \"Bad Request\"), message: Http11Message { is_proxied: false, method: None, stream: Wrapper { obj: Some(Reading(ChunkedReader(chunk_remaining=0))) } } })" })```
This is despite trying to use a custom `Delegate` to dig into the response deeper.

I believe this is an example of OP's (2).

**Comment by Byron** [comment]
Thanks, @binarybana!

As it turns out, I _may_ have additional time in the coming weeks and will work on a pure-rust rewrite of this crate.
That should help to address most if not all of the problems found in the wild.

**Comment by binarybana** [comment]
That would be incredible! Let us know if you need help or early testers.

**Comment by bjornax** [comment]
With some luck, PR #254  may help with 2), or at least point towards a possible solution.

**Comment by Byron** [comment]
I am closing this issue as the linked PR was merged and that hopefully helps a little already.
