### ISSUE TITLE
Unable to implement YouTube Delegate trait method

### ISSUE THREAD

**Issue by kellytk** [Byron/google-apis-rs#221]
The types [`JsonServerError` and `ServerError`](https://docs.rs/google-youtube3/1.0.8+20180511/google_youtube3/trait.Delegate.html?search=#method.http_failure) don't appear to be importable from anywhere, making it impossible to implement that method of the trait.

**Comment by Byron** [comment]
Thanks for the hint! This was fixed in [this commit](https://github.com/Byron/google-apis-rs/commit/7a44b3eae14e386ba634ace358c713324a6a0395), and will be part of the next release which I am trying to get out of the door today.
