### ISSUE TITLE
Datastore - Insert or upsert fails with 'Bad Request'

### ISSUE THREAD

**Issue by n-k** [Byron/google-apis-rs#226]
I have been trying to use datastore using the library generated from this repo. And any insert or upsert operations result in a 'Bad Request' response.

A sample of my code can be seen here: https://github.com/n-k/dstest/blob/master/src/db.rs#L32

The response I get is:
```
Err(Failure(Response { status: BadRequest, headers: Headers { Vary: X-Origin
Vary: Referer
Vary: Origin,Accept-Encoding
, Content-Type: application/json; charset=UTF-8
, Date: Wed, 22 May 2019 14:27:03 GMT
, Server: ESF
, Cache-Control: private
, X-XSS-Protection: 1; mode=block
, X-Frame-Options: SAMEORIGIN
, X-Content-Type-Options: nosniff
, Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
, Accept-Ranges: none
, Transfer-Encoding: chunked
, }, version: Http11, url: "https://datastore.googleapis.com/v1beta3/projects/<project_id>:commit?alt=json", status_raw: RawStatus(400, "Bad Request"), message: Http11Message { is_proxied: false, method: None, stream: Wrapper { obj: Some(Reading(ChunkedReader(chunk_remaining=0))) } } }))
```

**Comment by emilyaherbert** [comment]
I am pretty sure I figured out the issue! The bug is in this [function](https://github.com/Byron/google-apis-rs/blob/master/gen/datastore1/src/cmn.rs#L734), which is used by CommitRequest [here](https://github.com/Byron/google-apis-rs/blob/master/gen/datastore1/src/lib.rs#L3554).

Requests that contain `Null` are invalid, and because `remove_json_null_values` doesn't search the contents of `json::value::Value::Array(...)`, the `Null` values inside of the `Entity` `properties` are not getting removed.

**Comment by emilyaherbert** [comment]
I'm still testing this theory, but there is already a PR #217.

**Comment by n-k** [comment]
PR #217 has been open for a couple of months now. There also seem to be other PRs which are now open for about 4 months. Not sure if @Byron is accepting PRs to this repo.

**Comment by n-k** [comment]
I can confirm that PR #217 fixes this problem. Applied the patch locally, regenrated crates, and ran the test with local version of crate - it works as expected.

**Comment by Byron** [comment]
Sorry for the late response! I am grateful for every PR and will respond to all issues or requests eventually, even though sometimes, it takes an eternity!  Too many open source projects, and a growing unwillingness to sit in front of a computer outside of working hours.

In any case, the PR was merged, and I am currently publishing new versions of all crates within this repository. Please feel free to comment or reopen the issue if it doesn't turn out to be fixed.
The version to look for is `v1.0.9`.
