### ISSUE TITLE
google_sheets4::Request seems unnecessarily big

### ISSUE THREAD

**Issue by Goncalerta** [Byron/google-apis-rs#230]
The `google_sheets4::Request` structure is composed of an enormous number of fields, however, as indicated in the Google Sheets API Reference, those fields are ['union fields'](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request), so only one may be present for each `Request`. 

As the number of fields seems extremely large, I decided to lookup the `std::mem::size_of::<google_sheets4::Request>()`, which returned `13336`. This seems really too unnecessarily expensive, given that we will only use one field at a time.

I think this could be easily made much more efficient if those 'union fields' were represented as a rust `enum` (which also makes the "only one variant should be used per request" more clear to the users). Is there anything in the way the code is generated that makes it hard to do so? I genuinely don't know because, honestly, I don't really know how the API generator even works.

I don't think backwards compatibility should be seen as an issue, because the current type is so big to the point of being almost unusable. However, if that is the case, I see two other options:
- Making the new enum type and impl Into<new_type> for the old one (the function could then accept Into<new_type> as the parameter)
- Make a new function that takes in a &str with the structure as a JSON. As an user, I would gladly use serde represent the type in JSON myself and this way avoid the enormous memory waste.

**Comment by Byron** [comment]
I am quite sure I have answered this issue before, or something very much like it 😅. Generally, even though this case lends itself to a union, exactly how to do it should be extractable from the JSON schema provided by google.

In any case, this suggestion can probably be taken into consideration once this repository goes on to support `async` and is completely rewritten in Rust.

**Comment by Byron** [comment]
You might be interested in taking a look at the next generation of google-api crates:

https://github.com/google-apis-rs/generator
