### ISSUE TITLE
How do I rename a file? (google-drive3)

### ISSUE THREAD

**Issue by dvaerum** [Byron/google-apis-rs#232]
Hope someone can help, I am trying to rename a file on google drive using this library, but I simple cannot get it to work.

From what I can read on in the documentation here and the official one from Google it should be something like this, but the fucktion doit() is private and cannot only called by update() and upload_resumable(), but I don't want to overwrite the file, I just want to update its name.
```Rust
type HubType = DriveHub<Client, Authenticator<DefaultAuthenticatorDelegate, DiskTokenStorage, Client>>;

fn rename(hub: &HubType, file_id: &str, new_name: String) {
    let mut file = File::default();
    file.name = Some(new_name);

    let result = hub.files()
        .update(file, file_id)
        .supports_all_drives(true)
        .doit();

    info!("Rename - {:?}", result)
}
```

I hope someone can help, because from what I can see this will also be a problem if I want to move the file.

**Comment by dvaerum** [comment]
So I got it to work by taking the function [doit_without_upload](https://docs.rs/google-drive3-fork/1.0.10/src/google_drive3_fork/lib.rs.html#3428-3585) which I found in a forked version [google_drive3_fork](https://github.com/Byron/google-apis-rs/tree/master/gen/drive3).
I had to make some small changes for it to work, but after that it seems to work :D

I have created a patch if anyone should be interested [doit_without_upload.patch.txt](https://github.com/Byron/google-apis-rs/files/3439485/doit_without_upload.patch.txt). I was trying to figure out there in the generator I should make changes in order to get the doit_without_upload function included, but I am not able to find it.

Can anyone give me a pointer?

**Comment by Byron** [comment]
Sorry for the late reply, and great to hear that you found code that works. The next step could be to apply the change to the generator, which [can be found here](https://github.com/Byron/google-apis-rs/blob/1565e040c5b66fc03acec5eb9a8c2a5d570f3056/src/mako/api/lib/mbuild.mako#L503).

I am looking forward to a PR in case you find the time. In any case, I will be looking at the issues that came up while using various APIs while re-writing the crate to make use of `async`, and contain all lessons learned so far.

**Comment by dvaerum** [comment]
Hey @Byron it has been sometime since I look at this, but today I gave it another try. I was digging around in your generator and it was a little overwhelming, so I decided to watch your "Developer Diary" videos and it gave me some inside.
But, I am running into the problem that the method  `doit_without_upload`  which I wanted to add. From what I can see, this function is only going to be added one place in all of your auto-generated code. As such I would consider it an exception and I am not sure how you would like it handle that?

**Note:** It may be needed other places in the auto-generated code

btw, I loved your Developer Diary :smiley:

**Comment by Byron** [comment]
Thanks a lot for giving it a try! I can imagine how frightening such a codebase can be, just by seeing myself not wanting to touch it anymore (because of Python, mainly :D).

That said, the generator code has access to a vast amount of data about the API it's building in the moment, which may include access to per-API overrides or configuration flags. Thus it's absolutely possible to configure the APIs for which such exceptions should trigger the addition of new and specialized methods. Depending on the API documentation itself, it might also be possible to detect that case.

If you are truly looking at a single missing method in a single API, it might be easiest though to snatch the vendor the source code and modify the library by hand. The libraries are not changing often, and even if they do I would expect it to be straightforward to reapply the patch.

And the dev-diary videos, yeah, those were fun to make back in the days :), and I am glad they are still somewhat useful and fun :D.

What do you think?

**Comment by dvaerum** [comment]
> Thanks a lot for giving it a try! I can imagine how frightening such a codebase can be, just by seeing myself not wanting to touch it anymore (because of Python, mainly :D).

Don't mind Python that much, but you may need some comments in the code :wink: 

> That said, the generator code has access to a vast amount of data about the API it's building in the moment, which may include access to per-API overrides or configuration flags. Thus it's absolutely possible to configure the APIs for which such exceptions should trigger the addition of new and specialized methods. Depending on the API documentation itself, it might also be possible to detect that case.

Yes, I can differently see the possibility to create a few `if` statement there would make it so the `doit_without_uploads` function only would appear one place. I just don't see an easy way to figure out what all your variable names contain, but I guess that I should just hook-up a debugger to it.

> If you are truly looking at a single missing method in a single API, it might be easiest though to snatch the vendor the source code and modify the library by hand. The libraries are not changing often, and even if they do I would expect it to be straightforward to reapply the patch.

I don't know if it really is a one off situation, but in case it isn't I would like it to be possible for others to easily enable it there it is needed. Currently, I just patched it ones and that have been working ever since, but I would like to make it upstream, if possible :smiley: 

> And the dev-diary videos, yeah, those were fun to make back in the days :), and I am glad they are still somewhat useful and fun :D.
> 
> What do you think?

I am up for trying to make a pull request for your code generator, I just wanted you input before I spent too much time on it. You know, in case you wanted it differently than I would have done it.
I mean, I don't want to spend 2-3 days on it just to figure out that I should have done it differently :sweat_smile:

**Comment by Byron** [comment]
> Yes, I can differently see the possibility to create a few if statement there would make it so the doit_without_uploads function only would appear one place. I just don't see an easy way to figure out what all your variable names contain, but I guess that I should just hook-up a debugger to it.

Actually I never ran it with a debugger, so I wouldn't know if that's easy - probably it is. Usually printing to stdout or stderr worked to get an idea if what data is available. The command-line invocation is also visible when running make, which neatly shows which files are merged into the model, forming all data available to the templating engine.

> I am up for trying to make a pull request for your code generator, I just wanted you input before I spent too much time on it. You know, in case you wanted it differently than I would have done it.
I mean, I don't want to spend 2-3 days on it just to figure out that I should have done it differently 😅

Always a safe way to do it! By now this project is more or less in maintenance mode as I have no use for it anymore, but am happy about every contribution that extends its usefulness to others.

Given the [new and more recent efforts](http://github.com/google-apis-rs/generator), eventually this project might be obsolete. At least we will be able to salvage the existing crate names if desired as I am also part of the new organization and am happy to give up these crates in favor of the new ones.
Let's see… .

**Comment by dvaerum** [comment]
https://github.com/Byron/google-apis-rs/pull/255
Here you go, my pull request to your awesome project. I am ready for feedback or you can merge and let me have commit no. 800 :wink:

**Comment by dvaerum** [comment]
It is now possible to rename a file, without having to re-upload it :D
https://github.com/dvaerum/pipe2drive/blob/201c9b9c12cc41d7852ac6966fd07546c2c9d7dc/src/drive.rs#L103-L112

**Comment by Byron** [comment]
Thanks for all your help in resolving this issue! It was a pleasure working with you!
