### ISSUE TITLE
Optional openssl dependency

### ISSUE THREAD

**Issue by tylerhawkes** [Byron/google-apis-rs#236]
My team has a decent sized project and I've been able to not use openssl on every dependency except for this one. It's pulled in by `yup-oauth2` by default but it has a `rustls` feature that could be re-exposed. It would be great to have some more control over it.

**Comment by Byron** [comment]
[Work on the next version is currently underway](https://github.com/google-apis-rs/generator), and we will absolutely consider improving on this, while we are at it.

Is this a blocking issue for you?

CC @ggriffiniii

**Comment by Byron** [comment]
Work on the next version is currently underway, and we will absolutely consider improving on this, while we are at it.

Is this a blocking issue for you?

CC @ggriffiniii

**Comment by tylerhawkes** [comment]
It is not blocking us, however, it is certainly annoying to have to keep cross-compiling code in a docker image for openssl just for this one dependency.
