### ISSUE TITLE
Thread safety of cli calls

### ISSUE THREAD

**Issue by RomanHodulak** [Byron/google-apis-rs#240]
Hello, I have an app built on Rocket framework, which requires nightly Rust. However, at the time of writing the app, this library required stable Rust, so I opted to making drive3 calls inside the Rocket app via cli command. The calls are always readonly.

This works well, however, the Rocket app handles multiple requests in parallel. drive3 retrieves token that is valid for one hour. So it seems like when multiple calls in parallel are made to the drive3 when the token is no longer valid, multiple instances of drive3 refresh the token at the same time.

I believe this has produced an invalid drive3-token JSON. It looked like this:

```json
{
  "access_token": "<hidden>",
  "refresh_token": "<hidden>",
  "token_type": "Bearer",
  "expires_in": null,
  "expires_in_timestamp": 1568385913
}970
}
```

This produced an error:
```
Token retrieval failed with error: Could not serialize secrets: trailing characters at line 7 column 2
```

Is this problem solvable in the drive3 app? The requests on drive3 need to be run in parallel so I would like to prevent e.g. using mutex for the drive3 call.

Thanks for any help or suggestion.

**Comment by Byron** [comment]
Thanks for the detailed description! It’s amazing to hear you could put the CLI to good use!

Something I think you would have to do is to use the `—config-dir` flag, and use a separate one for each concurrent request. Probably you could use middleware to count the number of concurrent requests, and use that to differentiate each configuration directory. What’s unfortunate is that one cannot currently reuse the application information, which is read-only, requiring you to prepare each new configuration directory.

Maybe it’s worth building a custom binary that can only do what you need, without the issues you ran into.

**Comment by RomanHodulak** [comment]
Thank you for a quick reply. I did some digging and found out that my theory about the concurrency is wrong.

Issue persists even on single thread usage. I tried it through the command line. The mal-formatted JSON is created because the `access_token` has sometimes `137` characters and sometimes `132`. So when the old `access_token` is `137` and new token is `132`, 5 characters from the old JSON get copied into the new one.

For instance:

```json
{
  "access_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "refresh_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "token_type": "Bearer",
  "expires_in": null,
  "expires_in_timestamp": 1568468441
}
```

Gets refreshed to
```json
{
  "access_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "refresh_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "token_type": "Bearer",
  "expires_in": null,
  "expires_in_timestamp": 1568477393
}441
}
```

Notice the last three digits copied from the old `expires_in_timestamp` value.

Perhaps there is a bug in JSON token replace algorithm?

**Comment by Byron** [comment]
Oh wow, I was bitten by this issue so, so often now! It's actually the file not being truncated before writing. The linked commit should fix it.
If you are in the habit of building your own CLIs, you might be able to validate it. After cloning this repository, it should be as easy as `make drive3-cli` to rebuild the code.

**Comment by AlyoshaVasilieva** [comment]
I was running into this issue a lot last 2 or so weeks with the text-to-speech CLI. Grabbed the source from crates.io (to avoid trying to build on Windows) and applied the commit and can confirm it appears to fix the issue.
