### ISSUE TITLE
Credentials from the GCE metadata service

### ISSUE THREAD

**Issue by colbyn** [Byron/google-apis-rs#242]
Any updates on fetching credentials from the GCE metadata service?

Most rust AWS SDKs handle this internally (when running on EC2), which I'm accustomed to. So I'm a bit perplexed with regards to this crate.  

In my own library [ddb](https://github.com/colbyn/ddb) (which uses this crate) I've added some ad-hock steps. Although I think Google cloud run only works with the metadata service...

**Comment by Byron** [comment]
I am not familiar with the GCE metadata service, but would believe interacting with it presents an automation that is out of scope for this version of `google-apis-rs` unless it is being contributed and remains backwards compatible.

However, there is a new and upcoming iteration of Google-APIs [being cooked here](https://github.com/google-apis-rs/generated) and I welcome you to have a look. Maybe these could include the use-case you are mentioning from the get go.

Does this help?

**Comment by colbyn** [comment]
Ahh no worry, I’ve already figured it out [here](https://github.com/colbyn/ddb/blob/master/src/auth.rs) that seems to work. Personally I wish GCP used some common file system path for keys like what AWS does with e.g. `~/.aws/credentials`.

Anyway I’ve been looking at the google-apis-rs crates… Any idea when they’ll be published to crates and/or what’s blocking such?

**Comment by Byron** [comment]
Thanks for sharing your solution!

I don't know when the new crates will be published - for now they can be used by folks who generated the code themselves and keep it with their project. Alternatively, one could include the generated code as module so no additional crate is needed.

As a conclusion, I think we could close this issue and potentially recreate it to the new google api project as it crops up again?

**Comment by colbyn** [comment]
Certainly, and thanks for the reply!
