### ISSUE TITLE
writing a library that can take oauth or service account keys

### ISSUE THREAD

**Issue by yasushi-saito** [Byron/google-apis-rs#244]
This is more of a question.

 I'm writing a library that takes either a service account key *or* user oauth key, and performs various gcs operations. The problem I'm having is that both yup_oauth2 and google_storage1 types are parameterized by the authenticator all the way down. I don't see an easy way to have one type that can deal with multiple authenticator types. Is there a way to do what I'm trying to do?

**Comment by Byron** [comment]
I understand that the authentication method is built-in the standard authenticator implementations passed to the client. Thus each hub can only handle one authentication type by default. However, it should be trivial to implement a compound-authenticator which can handle multiple authentication types based other logic.

Something I could imagine working is to use the 'key' parameter in most (if not all) calls to the Google API to provide a custom authentication token. Please note that coming from me, this is no more than a guess right now.

Last but not least, there is an [alternative implementation](https://github.com/google-apis-rs/generator) of the Google-APIs incubating, which doesn't incorporate the concept of authentication at all, leaving it to the user entirely.

As I consider this Q&A, I am closing this issue, but hope you will keep posting comments or follow-ups as you see fit.
