### ISSUE TITLE
Error 404 Not Found when Using CloudKMS Symetric Derypt

### ISSUE THREAD

**Issue by ghost** [Byron/google-apis-rs#246]
I am trying to encrypt and decrypt a small text using the CloudKMS API provided by this repo. I am able to encrypt using  
``` rust
let req = EncryptRequest {
            plaintext: Some(base64::encode(data)),
            additional_authenticated_data: None
        };
        let res = self.hub
            .projects()
            .locations_key_rings_crypto_keys_encrypt(
                req,
                self.symmetric.as_str()
            ).doit()?;
```

However when I try to decrypt the output in the integration test I obtaint `Error404` from Google API. The Decrypt is done as follows:
```rust
        let req = DecryptRequest {
            ciphertext: Some( String::from_utf8(data.to_vec()).unwrap()),
            additional_authenticated_data: None
        };
        let res = self.hub
            .projects()
            .locations_key_rings_crypto_keys_decrypt(
                req,
                self.symmetric.as_str()
        ).doit()?;
```

and error obtained is 
```
Error: GoogleKMS(Failure(Response { status: NotFound, headers: Headers { Date: Thu, 02 Jan 2020 10:08:22 GMT
, Content-Type: text/html; charset=UTF-8
, Server: ESF
, Content-Length: 1696
, X-XSS-Protection: 0
, X-Frame-Options: SAMEORIGIN
, X-Content-Type-Options: nosniff
, Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
, }, version: Http11, url: "https://cloudkms.googleapis.com/v1/projects/{OurProject}/locations/northamerica-northeast1/keyRings/{OUR_KEYRING}/cryptoKeys/{OUR_KEY}/cryptoKeyVersions/1:decrypt?alt=json", status_raw: RawStatus(404, "Not Found"), message: Http11Message { is_proxied: false, method: None, stream: Wrapper { obj: Some(Reading(SizedReader(remaining=0))) } } }))
```

I am sure that `self.symmetric` is pointing to the same key, I have also trying to create a new one and hardcoded into the code. Same result. ServiceAccount used in my testing has Project Owner role, to make sure that it cannot be Privilages problem.

Any help would be much appriciated.

**Comment by Byron** [comment]
Sorry for the _very late reply_! This one went under the radar.

Maybe you could try with the latest version of the crates now available with async support in v2.0 or the next generation of [API generators](https://github.com/google-apis-rs).

As this repository is now in _maintenance mode_, this issue is probably not going to be fixed unless it is contributed.
