### ISSUE TITLE
Getting a playlist from youtube: MissingToken

### ISSUE THREAD

**Issue by Ploppz** [Byron/google-apis-rs#251]
I'm trying to retrieve a playlist just to acquaint myself with the API and this crate.

```rust
use std::default::Default;
use yup_oauth2::{Authenticator, DefaultAuthenticatorDelegate, ApplicationSecret, MemoryStorage};
use google_youtube3::YouTube;
 
fn main() {
    let secret: ApplicationSecret = Default::default();
    let auth = Authenticator::new(&secret, DefaultAuthenticatorDelegate,
                                  hyper::Client::with_connector(hyper::net::HttpsConnector::new(hyper_rustls::TlsClient::new())),
                                  <MemoryStorage as Default>::default(), None);
    let mut hub = YouTube::new(hyper::Client::with_connector(hyper::net::HttpsConnector::new(hyper_rustls::TlsClient::new())), auth);
    let (_, playlists) = hub.playlists().list("snippet").id("PLB9cXA-RF0jP34V4HqlByIu8uDwEMJF-B").doit().unwrap();
    println!("{:?}", playlists);
}
```

I get error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MissingToken(StringError { error: "invalid_request\n" })', src/main.rs:11:26
```

I expected this to work because in my understanding it should produce a similar api call as here https://developers.google.com/youtube/v3/guides/implementation/playlists#playlists-retrieve-single-playlist

**Comment by Byron** [comment]
Looking at the error type, `MissingToken(StringError {…})` I believe a token could not be acquired.
Did you create an application in the google developer console, enabled the youtube API and made the JSON describing all of that available to the running application? I think on first run, it places a sample file into `~/.google-apis`, which needs to be replaced with the one from the Google Developer Console.

I hope that helps.

Even though I close this issue, please feel free to post additional comments or follow up questions.

**Comment by Ploppz** [comment]
Thanks. Indeed I didn't think about acquiring an API key. I now have an API key, and I see in ` yup_oauth2::DiskTokenStorage` that I need a JSON file. You mentioned `~/.google-apis` but it does not exist. How can I create such a json file?

**Comment by Ploppz** [comment]
@Byron  I guess what I would need is oauth2 JSON. Apparently I can only get that in the google console if I have an application that needs access to private data.
It would be much simpler if I could just use an API key; that you get if you only need to use public data.  Is that not currently possible?

**Comment by Byron** [comment]
The API as implemented here downright forces you to provide some means of authentication, as it usually wants to use at least one OAUTH2 scope even for publicly available information.
When implementing your own authenticator, you should be able to control this precisely, even though I never tried to pass _no_ authentication token.

The [latest incarnation](https://github.com/google-apis-rs/generator) of these APIs doesn't enforce any authentication, and simply allows to set API keys (or not). Maybe this will make your tests easier.

Generally I would advise to use the command-line interfaces for testing, I think these are the ones who dump data into `~/.google-apis`, and the library won't touch your disk which seems to be your usecase. Apologies for realizing this that late in the conversation 😅
