### ISSUE TITLE
google-drive3-cli internal-error : entered unreachable code

### ISSUE THREAD

**Issue by stenhartn** [Byron/google-apis-rs#253]
i tried google-drive3-cli feature to copy file, it was fine. but when i tried to specify parents, it gave me :
thread 'main' panicked at 'internal error: entered unreachable code', .cargo/registry/src/github.com-1ecc6299db9ec823/google-drive3-cli-1.0.13+20200326/src/cmn.rs:321:34

stack backtrace:
   0:     0x5592609b3704 - backtrace::backtrace::libunwind::trace::h08d8048b5121e643
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5592609b3704 - backtrace::backtrace::trace_unsynchronized::hc9d78ceb51d88461
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5592609b3704 - std::sys_common::backtrace::_print_fmt::ha43ceab9bb17232c
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5592609b3704 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2d73b5341135d9e5
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5592609daa0c - core::fmt::write::h6578018894309c5e
                               at src/libcore/fmt/mod.rs:1069
   5:     0x5592609acac3 - std::io::Write::write_fmt::heb06cc71aa4bf844
                               at src/libstd/io/mod.rs:1439
   6:     0x5592609b5f75 - std::sys_common::backtrace::_print::hf7f997cd7d81e995
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5592609b5f75 - std::sys_common::backtrace::print::h3198c4c06099996d
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5592609b5f75 - std::panicking::default_hook::{{closure}}::hcca6be51547c9c86
                               at src/libstd/panicking.rs:198
   9:     0x5592609b5cb2 - std::panicking::default_hook::h7d306c5b3b53a68d
                               at src/libstd/panicking.rs:218
  10:     0x5592609b65d2 - std::panicking::rust_panic_with_hook::hc7cd1787ca846559
                               at src/libstd/panicking.rs:511
  11:     0x55926076788e - std::panicking::begin_panic::he7d7c33ff1ef55ca
  12:     0x559260809907 - drive3::cmn::FieldCursor::set_json_value::h4e7c65b869ab7244
  13:     0x5592606e1fe9 - drive3::Engine::_files_copy::h3257390310fa934e
  14:     0x5592606fa62c - drive3::Engine::_doit::h035f87e47a515937
  15:     0x55926074385f - drive3::main::h8086fd5e234d58f5
  16:     0x559260813c73 - std::rt::lang_start::{{closure}}::h051e602faf4af7c8
  17:     0x5592609b6a18 - std::rt::lang_start_internal::{{closure}}::hdbdedfd424f7ba40
                               at src/libstd/rt.rs:52
  18:     0x5592609b6a18 - std::panicking::try::do_call::h479675017aaf196d
                               at src/libstd/panicking.rs:331
  19:     0x5592609b6a18 - std::panicking::try::h32e657e7bd50e067
                               at src/libstd/panicking.rs:274
  20:     0x5592609b6a18 - std::panic::catch_unwind::h05b269a87f08ec3c
                               at src/libstd/panic.rs:394
  21:     0x5592609b6a18 - std::rt::lang_start_internal::ha5ee4d180f0ca9cb
                               at src/libstd/rt.rs:51
  22:     0x559260744472 - main
  23:     0x7f9e66923023 - __libc_start_main
  24:     0x5592606521ae - _start
  25:                0x0 - <unknown>

please help..thankss

**Comment by Byron** [comment]
Would you have a command-line to reproduce the issue?

Thanks

**Comment by stenhartn** [comment]
hi thanks for prompt reply..here is 1 example of how i get the error
`RUST_BACKTRACE=full drive3 files copy "file_id" -r parents="folder_id" mime-type='video/mp4'`

**Comment by stenhartn** [comment]
@Byron  sorry i cant be of much help, since i dont really understand. but may i know what is actually happening there? and any suggestion on where do i start, or what do i have to do to get a little enlightenment? thanks alot..

**Comment by Byron** [comment]
I have had a quick look to see where it reaches the unreachable code :D, and it's [one of these two](https://github.com/Byron/google-apis-rs/blob/8e9ce08aa21efc6309dc675b400a4bfbc457a1a0/src/rust/cli/cmn.rs#L333:L333).

This would mean there is an issue with it failing to create the object structure that it sets out to create, for some reason. Unfortunately I have written this code so long ago that I don't recall any peculiarities or how it is supposed to work.

**Comment by Byron** [comment]
As this repository has entered `maintenance mode` I won't be attempting to fix this issue outside of contributions which are always welcome. Unfortunately there is no CLI generator that I know of, but you might be able to implement what you need yourself either using these crates here or with what's present in the [next generation of generators](https://github.com/google-apis-rs).
