### ISSUE TITLE
google-sheets4 API is outdated

### ISSUE THREAD

**Issue by allebdev** [Byron/google-apis-rs#260]
I've noticed that `filterSpecs` field is missing in `PivotTable` struct. And it's also impossible to use deprecated API via `criteria` field in `PivotTable` because fields `condition` and `visibleByDefault` are missing in `PivotFilterCriteria` struct as well.
Please generate a new version of Google Spreadsheets API.

**Comment by Byron** [comment]
Thanks for letting me know. This should be fixed when using #259 as the PR doesn't only apply fixes but would also trigger regenerating all APIs.

Right now I am in the situation of being unable to run the toolchain as it's incompatible with ARM.

As I would like to keep maintaining this project I presume I should try to upgrade dependencies and do so in #259 - maybe subscribe there to stay posted on the progress.

**Comment by Byron** [comment]
By the way, there is a [new incarnation of this project](https://github.com/google-apis-rs/generator) which might already be able to build exactly what you need. Please take a look.

**Comment by Byron** [comment]
Can you check again? A new `async` version of the crate was published as [v2.0.4 I believe](https://crates.io/crates/google-sheets4).
