### ISSUE TITLE
Slides api support

### ISSUE THREAD

**Issue by LegNeato** [Byron/google-apis-rs#268]
There does not appear to be google slides support, though when I use the Google discovery service it exists in the json.

**Comment by Byron** [comment]
The `slides` API is currently deactivated as the generated code is invalid.

https://github.com/Byron/google-apis-rs/blob/5dc84bd041a0385b1d5100a4c4a07df3d81bbc1a/etc/api/shared.yaml#L36:L37

As of now, this is still the case:

```
cd gen/slides1 && cargo check
    Checking google-slides1 v2.0.2+20210322 (/Users/byron/dev/github.com/Byron/google-apis-rs/gen/slides1)
error[E0072]: recursive type `Page` has infinite size
    --> src/api.rs:1255:1
     |
1255 | pub struct Page {
     | ^^^^^^^^^^^^^^^ recursive type has infinite size
...
1282 |     pub slide_properties: Option<SlideProperties>,
     |                           ----------------------- recursive without indirection
     |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `Page` representable
     |
1282 |     pub slide_properties: Box<Option<SlideProperties>>,
     |                           ^^^^                       ^

error[E0072]: recursive type `SlideProperties` has infinite size
    --> src/api.rs:2050:1
     |
2050 | pub struct SlideProperties {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^ recursive type has infinite size
...
2059 |     pub notes_page: Option<Page>,
     |                     ------------ recursive without indirection
     |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `SlideProperties` representable
     |
2059 |     pub notes_page: Box<Option<Page>>,
     |                     ^^^^            ^

error: aborting due to 2 previous errors
```

**Comment by Byron** [comment]
As it's unlikely this will get fixed outside of contributions now that this repository is in maintenance mode, I may also point you to [alternative implementations](https://github.com/google-apis-rs) which probably provide a version of this API already.

**Comment by c-git** [comment]
@Byron I'm a lil lost regarding the alternative implementations. Is there a "recommended" way to make use of them? I kinda got the impression they are a work in progress.

**Comment by Byron** [comment]
Actually, it looks like Google is now [actively working on](https://github.com/googleapis/google-cloud-rust) their own implementation under the `google-cloud-*` namespace.

**Comment by c-git** [comment]
Oh that's great. Thanks for pointing it out. I'll look into it. (Guess my search wasn't so good, it didn't turn up that one)
