### ISSUE TITLE
google-drive3 panics when borrowing auth as mutable twice

### ISSUE THREAD

**Issue by harababurel** [Byron/google-apis-rs#269]
I've run into another problem with `google-drive3-2.0.2+20210322`. I'm updating the content of an existing file using [gcsf](https://github.com/harababurel/gcsf):

```console
$ echo "test" > /mnt/gcsf/some_file.txt
```

Internally, this calls the following (slightly simplified) method:

```rust
fn update_file_content(
    &mut self,
    id: DriveId,
    data: &[u8],
) -> Result<(Response<Body>, drive3::api::File), Error> {
    let file = drive3::api::File {
        mime_type: ...,
        ..Default::default()
    };

    self.tokio_runtime
        .block_on(
            self.hub
                .files()
                .update(file, &id)
                .add_scope(drive3::api::Scope::Full)
                .upload_resumable(DummyFile::new(data), some_mime_type),
        )
        .map_err(|e| err_msg(format!("{:#?}", e)))
}
```
Stack trace and panic: [pastebin](https://pastebin.com/raw/2Enkmb96).

The panic happens at [src/api.rs:10891:59](https://github.com/Byron/google-apis-rs/blob/5dc84bd041a0385b1d5100a4c4a07df3d81bbc1a/gen/drive3/src/api.rs#L10891):

https://github.com/Byron/google-apis-rs/blob/5dc84bd041a0385b1d5100a4c4a07df3d81bbc1a/gen/drive3/src/api.rs#L10891

A quick look through that file shows that the same `auth` object is borrowed as mutable a bit earlier in the same method:

https://github.com/Byron/google-apis-rs/blob/5dc84bd041a0385b1d5100a4c4a07df3d81bbc1a/gen/drive3/src/api.rs#L10782

Not sure what the solution is, considering that we are dealing with generated code. Maybe the fix is as simple as updating [mbuild.mako](https://github.com/Byron/google-apis-rs/blob/main/src/mako/api/lib/mbuild.mako) to use the same borrow in both places? Maybe the borrows don't have to be mutable?

In my case, I think I can get away with using `upload()` instead of `upload_resumable()`. This doesn't seem to run into the same bug. Still, this issue might be affecting other clients.

**Comment by Byron** [comment]
Thanks for the report! This seems like an unnecessary issue due to oversight. I don't remember to have ever used the resumable capabilities so there might be more trouble on the way.

I have attached the fixed regenerated version of the file and maybe you can give it a try at some point. If it works, I will push a new patch release.

[api.rs.gz](https://github.com/Byron/google-apis-rs/files/6293368/api.rs.gz)

**Comment by Byron** [comment]
In the latest release v2.0.4 there have been a lot of changes to make APIs thread-save and much more usable in the typical async program. Due to the absence of RefCell, I expect this issue to be resolved.

Please let me know if that's not the case though.
