### ISSUE TITLE
Compile `google-firestore1_beta1` to wasm

### ISSUE THREAD

**Issue by Septias** [Byron/google-apis-rs#287]
This is just a quick question, whether it would be possible to make `google-firestore1_beta1` compile for the wasm-target.
At the moment it doesn't work because it depends on `Socket.rs` which is not implemented for wasm.
Is it possible in a reasonable amount of time to make it work?

**Comment by Byron** [comment]
I don't think it's something that can be fixed here. Apparently [there is a very longstanding issue][issue] in hyper asking for the same thing.
And after checking feature flags in [hyper] and [hyper-rusttls] I can confirm that there is no flag to toggle on WASM support or toggle off the usage of socket-rs.

As there is nothing that can be done here I am closing the issue, please feel free to keep posting comments if something new comes up or if the situation changes.

[hyper-rusttls]: https://docs.rs/crate/hyper-rustls/0.22.1/source/Cargo.toml
[hyper]: https://docs.rs/crate/hyper/0.14.7/source/Cargo.toml
[issue]: https://github.com/hyperium/hyper/issues/1245

**Comment by Septias** [comment]
Yeah, that's pretty much what I thought would be the case. Thanks for your effort, I will come back here when I find a solution :)
