### ISSUE TITLE
MultiPartReader produces invalid multipart bodies

### ISSUE THREAD

**Issue by Recmo** [Byron/google-apis-rs#291]
https://github.com/Byron/google-apis-rs/blob/main/gen/storage1/src/client.rs#L452

This write terminates the part headers with a single `\r\n` where a double `\r\n\r\n` is required. Consequentially every simple object insert call fails with status 400 and response body `Malformed multipart body.`.

The reader also incorrectly adds an `\r\n` at the beginning and omits the one at the end of the last line, but this doesn't seem to bother the Google server.

In an unrelated issue: the error gets consumed from the response stream but does not get parsed since it is not JSON. A `client::Error::Failure(response)` is returned, but the `response.body` can no longer be read and the original server error message is lost.

**Comment by Byron** [comment]
Thanks a lot for bringing it up and for the fix!
Quite amazing that such a blatant issue could survive for so long.

**Comment by Byron** [comment]
The crate with patch applied [was released](https://crates.io/crates/google-storage1).
