### ISSUE TITLE
Publish fix for #291 for other APIs

### ISSUE THREAD

**Issue by pingw33n** [Byron/google-apis-rs#293]
Not sure about other APIs but at least Drive API v3 also needs #291 fix to make multipart uploads working.

**Comment by Byron** [comment]
Thanks for letting me know. drive3 v2.0.7 was just released, containing the fix. https://docs.rs/google-drive3/2.0.7+20210322 and https://crates.io/crates/google-drive3/2.0.7+20210322 for reference.
