### ISSUE TITLE
 google_storage1::client::Storage is not Clone

### ISSUE THREAD

**Issue by Recmo** [Byron/google-apis-rs#295]
[Looking at the implementation](https://docs.rs/google-storage1/2.0.5+20210330/src/google_storage1/api.rs.html#139-145) all members implement an efficient `Clone`. The Hyper and Authenticator will share the connection pool and token cache between clones. Storage can have a `#[derive(Clone)]`.

**Comment by Byron** [comment]
Please take a look at https://crates.io/crates/google-storage1/2.0.7+20210330 which has `Clone` implemented.
