### ISSUE TITLE
Release with yup-oauth2 0.6

### ISSUE THREAD

**Issue by Matts966** [Byron/google-apis-rs#316]
Current latest [google-apis-rs](https://github.com/Byron/google-apis-rs) is with yup-oauth2 0.5.

yup-oauth2 0.5 does not support ADC (Application Default Credentials) flow, in which credentials are loaded out of the box, but yup-oauth2 0.6 does.

@Byron 
Could you kindly make a release with yup-oauth2 0.6?

**Comment by Byron** [comment]
Indeed, the yup-oauth2 has already landed in `main` and I hope you are ok with subscribing/tracking #314 for notification on when a new release has landed.

Thank you.

**Comment by Matts966** [comment]
@Byron Sorry for my inaccurate issue.
Current `main` depends on `yup-oauth2` 5, and is not compatible with `yup-oauth2` 6.
https://github.com/Byron/google-apis-rs/blob/743a56f4b7415dd63ccb718578be8c287cbc6da0/Cargo.toml#L25

Could you please re-check this issue?

**Comment by Byron** [comment]
Oh, that is a little confusing indeed as the top-level manifest isn't relevant or used at all.

With the latest release, yup-oauth2 should be at version 6 throughout.

**Comment by Matts966** [comment]
I see! Thank you for your explanation :)
