### ISSUE TITLE
mismatched types: HttpsConnector

### ISSUE THREAD

**Issue by alexkingnz** [Byron/google-apis-rs#334]
Getting the following error when trying to build/install with `cargo install google-sheets4-cli`:

```   Compiling google-sheets4-cli v3.0.0+20220221
error[E0308]: mismatched types
    --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/google-sheets4-cli-3.0.0+20220221/src/main.rs:1619:43
     |
1619 |             hub: api::Sheets::new(client, auth),
     |                                           ^^^^ expected struct `HttpsConnector`, found struct `hyper_rustls::connector::HttpsConnector`
     |
     = note: expected struct `Authenticator<HttpsConnector<HttpConnector>>`
                found struct `Authenticator<hyper_rustls::connector::HttpsConnector<HttpConnector>>`
     = note: perhaps two different versions of crate `hyper_rustls` are being used?

For more information about this error, try `rustc --explain E0308`.
error: failed to compile `google-sheets4-cli v3.0.0+20220221`, intermediate artifacts can be found at `/tmp/cargo-installU9SBBQ`

Caused by:
  could not compile `google-sheets4-cli` due to previous error
```

**Comment by Byron** [comment]
Thanks for reporting. This has now been fixed and version 3.1 of the sheets4 API has been published to crates.io.

This should resolve this particular issue, but if not please let me know in the comments.

**Comment by DeboMac** [comment]
Hello, and thanks everyone for fixing this issue !

@Byron do you think it would be possible to release a new version for `googledrive-3` ? I am also encountering this issue.

Thanks a lot

**Comment by Byron** [comment]
No problem, @DeboMac , it's done !

**Comment by SriRamanujam** [comment]
Hi, I'm running into this issue with `texttospeech1` as well, could you release a new version of that? Thanks so much for maintaining this library!

**Comment by Byron** [comment]
Alright, no problem, the crate has been released.

And since these crates really are used by folks apparently I will republish them all now.

**Comment by dominikonysz** [comment]
Hello @Byron,

I'm having the same problem with `vision1` as the 3.1 version is not published to crates.io. Can you also republish it please? Thanks!

**Comment by Byron** [comment]
No problem, the [`vision1`](https://crates.io/crates/google-vision1/4.0.1+20220225) API has been released to crates.io
