### ISSUE TITLE
Support HTTP proxies

### ISSUE THREAD

**Issue by kylegentle** [Byron/google-apis-rs#337]
As written, Hubs require clients to use a `hyper_rustls::HttpsConnector`:

https://github.com/Byron/google-apis-rs/blob/93de38dddd36ab21eb99f782a3a6dbdc4173220f/src/mako/api/api.rs.mako#L52

Unfortunately, this connector doesn't support HTTP proxies (see [related issue](https://github.com/rustls/hyper-rustls/issues/172)).

Can we make Hub::new() more generic, to enable customized connectors like those of [`hyper_proxy`](https://docs.rs/hyper-proxy/latest/hyper_proxy/)? This would also follow the convention of [hyper's own builder](https://docs.rs/hyper/latest/hyper/client/struct.Builder.html#method.build).

**Comment by Byron** [comment]
Thanks for bringing this up! I didn't look into the details yet, but if you think this can be solved by following hypers own conventions, the google crates should certainly follow suit.

PRs are welcome. In case you want to take it on, please only submit changes to `src/` without regenerating the APIs. Thank you.

**Comment by kylegentle** [comment]
Thanks for the quick response, @Byron! 

I'm pretty new to Rust, and totally new to Mako, but I'll share what I've got so far. From there, if you can provide some guidance I'd be happy to write a fix, or if you decide it would be more efficient to do it yourself, of course that's great too.

The approach I have in mind is to update Hub's `client` type to:
`hyper::Client<tower::Service<http::Uri>, hyper::body::Body>`

This is more or less what hyper does with the `connector` parameter of their client builder ([code pointer](https://github.com/hyperium/hyper/blob/ed2fdb7b6a2963cea7577df05ddc41c56fee7246/src/client/connect/mod.rs#L280-L297)).

[Link to the `tower::Service` trait](https://docs.rs/tower/0.4.6/tower/trait.Service.html) for reference.

So my thinking is that we:

1. Add `tower` as a dependency in Cargo.toml.
2. Add `use tower::Service` and `use http:Uri` to [src/rust/api/client.rs](https://github.com/Byron/google-apis-rs/blob/main/src/rust/api/client.rs).
3. Update the mako templates to appropriately generate these type annotations in the Hub code.
    a. Update [src/mako/api/api.rs.mako](https://github.com/Byron/google-apis-rs/blob/main/src/mako/api/api.rs.mako#L52), for the struct members and `new` function.
    b. Update the hub type parameters.

3b is the part I feel least equipped to tackle at this point, but I'd love a sanity check on the rest too. I'm sure I don't have a complete picture yet. :smile:

**Comment by Byron** [comment]
Thanks a lot for the summary!

It looks like `tower_service` adds the much needed abstraction layer to not bind so closely to the underlying transport, which sounds like the right approach.

Maybe there should also be a point 4) which updates the CLI code as it will instantiate an API hub as well.

As to how to proceed from here, maybe it helps to share my typical workflow. Usually I use the `groups_migration` codebase to try things. You could prototype the changes there and fiddle with the types until it works. The same could be done for the CLI of `groups_migration` for completeness. Once this works, these changes 'just' have to be transferred to the `mako` source, which usually is quite mechanical. `make` can be used to repeatedly `make groupsmigration1-cargo ARGS=check` for validation, along with `make groupsmigration1-cli-cargo ARGS=check` for the cli related code.

I hope that helps.

**Comment by kylegentle** [comment]
I discovered that this is also an issue in yup-oauth2; submitted a PR to fix it there as well.
