### ISSUE TITLE
[Feature] Support create_folder API call for `files` module

### ISSUE THREAD

**Issue by ciehanski** [Byron/google-apis-rs#356]
Could support be added regarding API calls for `files` module to allow for the creation of folders?

This is supported in the [`google_drive`](https://crates.io/crates/google-drive) crate via the [create_folder](https://docs.rs/google-drive/latest/google_drive/files/struct.Files.html#method.create_folder) function.

**Comment by Byron** [comment]
Unfortunately I don't know what that would mean. Can you post links to the original Google API for google drive presumably that shows the method? My guess is that the `google_drive` crate must be regenerated against a more recent version of the corresponding google API.

**Comment by ciehanski** [comment]
I'm silly, I was able to find the documentation on this [here](https://developers.google.com/drive/api/guides/folder). It appears you use the `files.create()` command and provide the MIME type `application/vnd.google-apps.folder` which will create the folder and return its ID. It appears the `google_drive` crate just provides a helper function to wrap this call and it's not a separate endpoint on the Google API. I'll close this, sorry about that 👍
