### ISSUE TITLE
Google drive crate don't implement Sync and Send trait

### ISSUE THREAD

**Issue by VidsSkids** [Byron/google-apis-rs#372]
I want to use 'DriveHub' in multi-threaded app but with the current crate version it produce an error.

This multi-threaded app is an actix-server and i want to put DriveHub inside app_data. The trait 'Send' is not implemented so it produce and error.
```
`(dyn GetToken + 'static)` cannot be sent between threads safely
the trait `Send` is not implemented for `(dyn GetToken + 'static)`
required for `Unique<(dyn GetToken + 'static)>` to implement `Send`
```

**Comment by Byron** [comment]
This was fixed in the latest patch release of the crate.
