### ISSUE TITLE
Bump google-apis-common to 4.0.1

### ISSUE THREAD

**Issue by philippeitis** [Byron/google-apis-rs#375]
Given that the current version of `google-apis-common` doesn't include the send/sync fixes, and will thus break anyone using the downstream crates, it needs a bump and new release (and also, `v4.0.0` should probably be yanked to prevent it being pulled in).

**Comment by Byron** [comment]
Thanks for the heads-up. That's definitely something I should remember in the future.

<img width="960" alt="Screen Shot 2022-10-02 at 09 19 17" src="https://user-images.githubusercontent.com/63622/193433920-61abad39-81b2-4fe7-8257-9666929e399f.png">

This should be it.
