### ISSUE TITLE
[request] Possibility of bumping the beta version?

### ISSUE THREAD

**Issue by fosskers** [Byron/google-apis-rs#414]
Thank you for this project.

It seems that with recent releases, only the build metadata for `google-drive3` has been updated and not the number that follows `-beta-`. This can cause [strange build bugs](https://github.com/rust-lang/cargo/issues/7180), and indeed we're hitting this in CI today. 

Would it be possible to push a new `-beta-2` release to get around this? Thank you kindly.

**Comment by Byron** [comment]
I couldn't follow what happen in the `strange build bugs` link provided, searching for `google` or `drive` didn't yield a result.

Is this request pre-emptive?

Besides, maybe it's time to release the actual version 5, without beta suffix, as the crates seem to be working generally by absence of bug reports.

**Comment by fosskers** [comment]
Thanks for your prompt response! 

To elaborate on the original issue: there is a long-standing bug in `cargo` where it occasionally gets confused about crates whose versions are the same, but the metadata tag (everything after the `+`) is different. As far as semver is concerned, these would technically be the "same version". `cargo` somehow downloads the wrong version, then complains about checksum failures.

Our personal issue is that everything works locally, but CI builds seem to be failing with the checksum bug. Overall strange :man_shrugging: 

Otherwise yes, the crate itself seems to work great! We were on v3 for a long time and recently upgraded to utilize some new features, but then hit the checksum bug. A general `5.0.2` release would be great! :pray:

**Comment by Byron** [comment]
Thanks for helping me understand, I heard about that issue as well, particularly in conjunction with these crates which also use `+<date>`.

[Here is the new release](https://crates.io/crates/google-drive3/5.0.2+20230115) of google-drive3.

**Comment by fosskers** [comment]
Thank you very much!
