### ISSUE TITLE
[Request] Possibility of bumping the beta version for `google-fcm1`?

### ISSUE THREAD

**Issue by DGulshan** [Byron/google-apis-rs#417]
Hi,
I need the fix that got merged in [this PR](https://github.com/Byron/google-apis-rs/pull/404) for my workflow, but it's only available in the beta versions. Right now, there are two beta versions for google-fcm1, `5.0.2-beta-1+20220228` & `5.0.2-beta-1+20230106`. Because of the same `cargo` issue mentioned in #414, I am running into checksum mismatch errors during build time.

Since there is a possibility of `cargo` matching the checksum with the correct version sometimes, only way for me to get the build done is keep retrying, until that happens.

Please would it be possible to release `5.0.3-beta-1` or any general release with the fixes from that PR?

Thank you for all the work on this crate.

**Comment by Byron** [comment]
Sure thing, here is [the new release](https://crates.io/crates/google-fcm1/5.0.2+20230106), and I hope that helps.

**Comment by DGulshan** [comment]
Thank you so much for quick resolution. 🙏
