### ISSUE TITLE
Cli tool not working 

### ISSUE THREAD

**Issue by Jashwanth537** [Byron/google-apis-rs#435]
Simple text translation over translate3 returns the following error: 

Please direct your browser to ?scope=https://www.googleapis.com/auth/cloud-platform&access_type=offline&redirect_uri=http://127.0.0.1:52692&response_type=code&client_id= and follow the instructions displayed there.

**Comment by Jashwanth537** [comment]
any documentation or test examples for the same will be greatly helpful. Thank you

**Comment by FrenchGithubUser** [comment]
I have the same "issue" with the crate. I'm trying to use my api key like so : 
```
    let secret: yup_oauth2::ApplicationSecret = yup_oauth2::ApplicationSecret {
        client_id: "client-id".to_string(),
        client_secret: "secret".to_string(),
        ..Default::default()
    };
    let auth = yup_oauth2::InstalledFlowAuthenticator::builder(
        secret,
        yup_oauth2::InstalledFlowReturnMethod::HTTPRedirect,
    )
    .build()
    .await
    .unwrap();
```

But I'm still prompted for going on an url. Is there a way to provide the api key in the code directly without user actions ? 

@Byron

**Comment by Byron** [comment]
> But I'm still prompted for going on an url. Is there a way to provide the api key in the code directly without user actions ?

After the first login it will store the key in plain text in some `~/.google*` folder, so if one would place the key there in advance it wouldn't prompt. One can also provide an implementation of an authenticator which is asked for the token directly. Details are in the code.
