### ISSUE TITLE
Upgrade to Hyper 1.0

### ISSUE THREAD

**Issue by thomas001** [Byron/google-apis-rs#459]
See https://seanmonstar.com/blog/hyper-v1/. The API changed, so this might mean a new major version in semver for google-apis-rs as well.

**Comment by Byron** [comment]
Thanks for the hint!

As these crates are in maintenance mode, contributions will be needed to make this happen. Thanks for your understanding.

**Comment by k-bx** [comment]
@thomas001 did you have any progress on this one by any chance?

**Comment by IvanUkhov** [comment]
I think it is `yup-oauth2` that should upgrade first. Created a tracking issue there: https://github.com/dermesser/yup-oauth2/issues/214.

**Comment by IvanUkhov** [comment]
`yup-oauth2` has been updated. So this is relevant now.
