### ISSUE TITLE
google-androidpublisher3 5.0.4 not working

### ISSUE THREAD

**Issue by Dreaming-Codes** [Byron/google-apis-rs#475]
Hi! I've just update the library and google_play_console_hub.purchases().products_get is now giving me a bad request error:
{\"error\":{\"code\":404,\"errors\":[{\"domain\":\"androidpublisher\",\"location\":\"token\",\"locationType\":\"parameter\",\"message\":\"The document type is not supported.\",\"reason\":\"unsupportedDocType\"}],\"message\":\"The document type is not supported.\"}}\n" error_details=Bad Request: {"error":{"code":404,"errors":[{"domain":"androidpublisher","location":"token","locationType":"parameter","message":"The document type is not supported.","reason":"unsupportedDocType"}],"message":"The document type is not supported."}}

Am I doing something wrong? Before updating that same request was working.

**Comment by Dreaming-Codes** [comment]
I just tried the previous version, and now it's not working anymore. What could be the issue? I doubt it's my code, since it was working a month ago and I haven't touched it.

**Comment by Byron** [comment]
This could be related to the fact that version 5.04 also updated the API itself - maybe it became incompatible in some way.
Using the previous version should work though, so probably something else happened that is unrelated.

As it's not possible to provide support beyond the generated code itself, I have to close this issue. Thanks for your understanding.
