### ISSUE TITLE
`Content-Length` header missing when no body was provided in post request, causing request failure

### ISSUE THREAD

**Issue by Dreaming-Codes** [Byron/google-apis-rs#476]
Hi, the latest schema update introduced a new method `google_play_console_hub..purchases().products_consume` which is a fundamental method to consume a bought product to allow the user to buy it again but that method always gives me the following error:

> Http status indicates failure: Response { status: 411, version: HTTP/1.0, headers: {"content-type": "text/html; charset=UTF-8", "referrer-policy": "no-referrer", "content-length": "1564", "date": "Sat, 09 Mar 2024 11:16:57 GMT"}, body: Body(Full(b"<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 411 (Length Required)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>411.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>POST requests require a <code>Content-length</code> header.  <ins>That\xe2\x80\x99s all we know.</ins>\n")) }

**Comment by Dreaming-Codes** [comment]
Comparing it with another post request in the generated code it seams like this part is missing
products_acknowledge:
https://github.com/Byron/google-apis-rs/blob/ef8dc60e716dba545453f70caca23ac97427fe6c/gen/androidpublisher3/src/api.rs#L36398-L36408


https://github.com/Byron/google-apis-rs/blob/main/gen/androidpublisher3/src/api.rs#L36696

**Comment by Byron** [comment]
There cannot be support for any of the generated APIs, they are provided by Google. This repository is about the generator itself, and no other support can be provided here.
Thanks for your understanding.

**Comment by Dreaming-Codes** [comment]
> Owner

Please read what I've wrote above as a comment

**Comment by Dreaming-Codes** [comment]
@Byron Please read what I wrote above as a comment

**Comment by Dreaming-Codes** [comment]
@Byron nope products_consume is a new method

**Comment by Dreaming-Codes** [comment]
@Byron I think that this is a bug in the generator since it's skipping a required post header

**Comment by Byron** [comment]
Please feel free to submit a PR with a fix. If that allegedly missing header can't be inferred from the API description, maybe the API can be changed to allow the user to inject their own headers.

**Comment by Dreaming-Codes** [comment]
> Please feel free to submit a PR with a fix. If that allegedly missing header can't be inferred from the API description, maybe the API can be changed to allow the user to inject their own headers.

@Byron The header missing is a required http header not a custom one, it's Content-length

**Comment by Dreaming-Codes** [comment]
I would fix that, but I really don't know how Mako works.

**Comment by Byron** [comment]
You can probably look at the generated code to see under which circumstances it does or doesn't add that header.

**Comment by Dreaming-Codes** [comment]
@Byron the only difference that I notice from other post requests is the missing request key
https://github.com/Byron/google-apis-rs/blob/ef8dc60e716dba545453f70caca23ac97427fe6c/etc/api/androidpublisher/v3/androidpublisher-api.json#L3888-L3890

https://github.com/Byron/google-apis-rs/blob/ef8dc60e716dba545453f70caca23ac97427fe6c/etc/api/androidpublisher/v3/androidpublisher-api.json#L3895-L3929

**Comment by Dreaming-Codes** [comment]
I think that I found the problem. basically when there's no body the generator does not add the Content-length header 

https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.products/consume#request-body

**Comment by Byron** [comment]
Thanks for the research.
That sounds like something fixable, even though a fix will have to be contributed.

**Comment by Dreaming-Codes** [comment]
I think that the error in the generation happens here
https://github.com/Byron/google-apis-rs/blob/ef8dc60e716dba545453f70caca23ac97427fe6c/src/generator/templates/api/lib/mbuild.mako#L752-L763

**Comment by Dreaming-Codes** [comment]
It may be enough to add `.header(CONTENT_LENGTH, 0_u64)` between lines 761 and 762.

**Comment by Byron** [comment]
It appears like it, and is a strange omission as well. You can probably try it locally, and even if not, CI will be able to validate the generated code is still correct.

**Comment by Dreaming-Codes** [comment]
@Byron I'm trying to get nix on my system to work so I can get python 3.8

**Comment by Byron** [comment]
Getting a local dev setup is harder than it should be due to needing python, thus I recommend creating a PR with this seemingly trivial change (blindly, if you will), and see if that works.

For local testing, the change can be added by hand in the generated code, and used with your application via `[patch."crates-io"]` section in the Cargo manifest.

**Comment by Dreaming-Codes** [comment]
> Getting a local dev setup is harder than it should be due to needing python, thus I recommend creating a PR with this seemingly trivial change (blindly, if you will), and see if that works.
@Byron I've create a pull request with a .devcontainer for easier development
